### ISSUE TITLE
Bikeshed: Rename Dimension to Mode when Mode is meant

### ISSUE THREAD

**Issue by peterahrens** [tensor-compiler/taco#105]
The taco api currently uses two different meanings of the word "dimension". taco uses "dimension" to mean either a mode of a tensor, or the length of a mode.

I propose that we rename the usage of "dimension" to the word "mode" when "mode" is meant.

This will maintain compatibility with tensor literature. The word "dimension" is more often used to refer to a size (people already talk about the "dimension" of a matrix or vector, but I rarely hear "first dimension" to refer to the row mode of a matrix) and the word "mode" is unambiguous in the context
of tensors.

**Comment by peterahrens** [comment]
related to #106

**Comment by peterahrens** [comment]
This means that we would rename `DimensionIndex` to `ModeIndex` and `DimensionTypes` to `ModeTypes` etc.

**Comment by fredrikbk** [comment]
We have a method `TensorBase::getDimension` that corresponds to this definition of a dimension. To avoid a lot of terminology, however, I propose we rename this method to `getModeSize` and remove references to dimension altogether.

**Comment by fredrikbk** [comment]
Updated the tensor and format APIs to reflect this in 1aa35c1. We still need to change the index API as described above by @peterahrens .

**Comment by fredrikbk** [comment]
Fixed in 1aa35c1 and 7521fb2. @peterahrens do reopen or send a pull request if I missed something.
