### ISSUE TITLE
New Tensor Compute API  (RFC)

### ISSUE THREAD

**Issue by fredrikbk** [tensor-compiler/taco#111]
This RFC discusses a Tensor APIs design that came up in a discussion with @stephenchouca. It is related to #72, which proposes a parameter system, and to [Halide's design](http://halide-lang.org/tutorials/tutorial_lesson_02_input_image.html). The lazy API discussed in #90 will be built on top of the APIs decided on here.

# Current Design

In the current API, a `Tensor` object is both a function to compute a tensor and the result of that function.  For example, to create and compile a function to compute a vector addition, I write:

```cpp
a(i) = b(i) + c(i);
a.compile();
```

The tensor `a` is now a function to compute `a`. To compute it, I write:

```cpp
a.assemble();
a.compute();
```

After these method calls, the results of computing `a` is stored in `a`.

# New Design

The alternative is to separate the function to compute `a` from the result of the function (`a`). To create and compile a function to compute a vector addition, I write something like:

```cpp
Func vecadd(a(i) = b(i) + c(i));
vecadd.compile();
```

or

```cpp
Func vecadd;
vecadd.addStatement(a(i) = b(i) + c(i));
vecadd.compile();
```

That is, the assignment operator returns a `Stmt` object that is bundled in the Func object. To compute with the function, I write something like:

```cpp
vecadd.assemble();
vecadd.compute();
```

After these method calls, the results of computing `vecadd` is stored in `a`. 

Since `a`, `b`, and `c` are all `Tensor` objects, as opposed to `TensorParam` objects (#72), they are inlined in the function and do not need to be supplied as arguments. To compute the same function with `TensorParam` objects, I write something like:

```cpp
Func vecadd(aparam(i) = bparam(i) + cparam(i));
vecadd.compile({bparam, cparam});

vecadd.assemble(a, b, c);
vecadd.compute(a, b, c);

vecadd.assemble(x, y, z);
vecadd.compute(x, y, z);
```

# Notes

- With the new design, we can create many functions with the same result tensor.
- We can support both designs. The current design is (perhaps) simpler, while the new design is more explicit and flexible.

**Comment by shoaibkamil** [comment]
Overall, I think this is the way to go.  Some clarifying questions:

- Why have both the ability to specify computations using `TensorParam` objects without a `Func` (#72) and with a `Func`?  It seems like having just the latter is sufficient, and would make it a bit simpler of an overall API: for concrete inputs, you can write the output as an index expression, and for a function that takes parameters, you write a `Func` with `TensorParam`s.

- Presumably, the compilation functions would be attached to a `Func`, correct?  So users can do `vecadd.compile_to_object(...)` to obtain an AOT-compiled object file

- What are the semantics of `Func::addStatement`?  If one writes:
```
Func vecadd;
vecadd.addStatement(a(i) = b(i) + c(i));
vecadd.addStatement(d(i) = a(i) * 4);
```
is there a single output tensor `d` or are both `a` and `d` outputs?

- I'm not sure I understand what you mean by "With the new design, we can create many functions with the same result tensor."

- On what object will scheduling functions be called?  It seems to make sense to do it on `Func` like Halide does, but depending on what the semantics of `addStatement` are, this might not be flexible enough.  Perhaps if `addStatement` is similar to the concept of a `Stage` in Halide, then we can schedule each statement.

**Comment by fredrikbk** [comment]
1. I agree that we don't need to support `TensorParam` for the tensor-as-a-function API. This does make the function API the primary API though, with the tensor-as-a-function API delegated to an easy shortcut. I also imagine most casual users will want to use the casual API in #90. Sophisticated users might prefer the explicit function API to the tensor-as-a-function API.

2. Yes, I think that makes sense (with camelCase). The new Tensor API is closer to the Halide APIs. The main difference is that the `Func` objects would be the result of the assignment operators, instead of the operating in-place on them. So

```cpp
Func vecadd(aparam(i) = bparam(i) + cparam(i));
```

instead of

```cpp
Func vecadd;
vecadd(i) = bparam(i) + cparam(i));
```

If we choose to go with the second alternative above, which I'm not adverse to, we would also have to tell the function what format the result should be.

3. The reason why I mentioned the `addStatement` is in anticipation of a future code generator that compiles several index expressions into one code that may have multiple results (so both `a` and `d` are outputs). This opens up further optimization opportunities and is a source of the increased flexibility of functions.

4. In the current design the index expression is added to a tensor, so each tensor can only be the target of one expression. But with the functions, I can compile two functions, say `vecadd` and `vecsub`, that have the same output/result tensor. That is

```cpp
Func vecadd(a(i) = b(i) + c(i));
vecadd.compile();

Func vecsub(a(i) = b(i) - c(i));
vecsub.compile();

while (notDone) {
  if (isFoo)
    vecadd();
  else 
    vecsub();
  ...
}

```

With the old API I couldn't do this without recreating and recompiling the expression every time I want to compute something new into `a`.

5. I don't have a clear idea of this. I imagine some scheduling constructs, like index variable splitting, will apply to `Expr` objects w.r.t. to an index variable. In fact, it may be that a lot of scheduling will be done on the index variables.

**Comment by shoaibkamil** [comment]
3. I would be in favor of explicitly asking users to define outputs; otherwise, it'll be difficult to disambiguate which is a temporary and which is an output.

5. I believe I understand what you mean here.  I hope to have a reasonable proposal for scheduling post-PLDI, but what I was referring to is that a `Func` should expose its statements for scheduling.  In other words, something like `vecadd.statement(0).vectorize(i, 4)` or similar.

**Comment by fredrikbk** [comment]
Superseded by RFC #126
