### ISSUE TITLE
Complex numbers

### ISSUE THREAD

**Issue by fwinter** [tensor-compiler/taco#116]
Hi! We are looking for a sparse tensor framework just like yours. However we rely on computations on complex numbers and a first attempt with the current taco code didn't quite succeed. I.e. I couldn't do

`Tensor<std::complex<double> > A({2,2},   sm);`

Is it already possible to define tensors on complex numbers? If not, would this represent a major feature addition (and thus will not be available for some time to come)?

**Comment by fredrikbk** [comment]
Hi @fwinter! I hope taco can help you.

We don't support anything except doubles yet, but I think it will be easy for us to add (hours/days, not weeks). We are, however, completely committed until the end of November. It is a clear hole in taco though, so I would like to fix it sometime in either December or early next year.

If this is the only thing blocking you from using taco, then I will make an effort to implement it next month.

**Comment by fwinter** [comment]
I believe if taco would support tensors of complex numbers and would expose the complex conjugation of a tensor (i.e. conjugate all elements) then we could use it in our contraction framework right away.

**Comment by quaxquax** [comment]
Want to second fwinter's request. TACO could be a great fit for Quantum Computing software (e.g. compilers for universal  quantum gate sets) if it could handle complex numbers.

**Comment by fwinter** [comment]
Since @quaxquax mentioned his field.. Our application involves Nuclear Physics calculations and we believe taco would be of great use.

**Comment by fredrikbk** [comment]
Those are really cool applications! Based on this I’ll try to prioritize complex numbers next month or January. Is the complex conjugation you refer to a component-wise per-non-zero conjugation?

**Comment by fwinter** [comment]
OK! For us, the earlier the better.
Yes, it's an element-wise complex conjugation. Only the non-zero elements require an actual operation since zero is it's own complex conjugate.

**Comment by RSenApps** [comment]
@fwinter @quaxquax Complex numbers should now be supported. I am still working on adding complex literals as well as cleaning up some things in the code, but for your use case, it should be good to use. Please reach out if you run into any issues or have any feedback, we are very interested to see what you use taco to build.

**Comment by quaxquax** [comment]
Thanks! Much appreciated.
