### ISSUE TITLE
data files for mttkrp sddmm spmv

### ISSUE THREAD

**Issue by werschulz** [tensor-compiler/taco#119]
Where might I find the files
../data/webbase.mtx
../data/pwtk.mtx
../data/facebook.tns
that  are read in mttkrp, sddmm, and spmv?
They aren't in the source distribution.

**Comment by stephenchouca** [comment]
Those files are from the [SuiteSparse Matrix Collection](https://sparse.tamu.edu/) and [FROSTT Tensor Collection](http://frostt.io/tensors/). We didn't include them in this repository for copyright reasons, though you can download them from here:

- https://sparse.tamu.edu/MM/Williams/webbase-1M.tar.gz
- https://sparse.tamu.edu/MM/Boeing/pwtk.tar.gz
- http://frostt.io/tensors/nell-2/

Both repositories also have other matrices and higher-order tensors that you can try out the example applications with.

**Comment by werschulz** [comment]
Hi.

Thanks.
-- 
Arthur G. Werschulz
Assoc. Chair for Undergrad Studies, Lincoln Center 
Dept of Computer and Information Sciences
Fordham University
O: (212) 636-6325
C: (908) 612-8140
