### ISSUE TITLE
missing data files for test/examples

### ISSUE THREAD

**Issue by tuglat** [tensor-compiler/taco#120]
The data files for the examples from your website seem to be missing. For example, pwtk.mtx and webbase.mtx.

**Comment by stephenchouca** [comment]
The first two files are from the [SuiteSparse Matrix Collection](https://sparse.tamu.edu/) and can be download here:

- https://sparse.tamu.edu/MM/Williams/webbase-1M.tar.gz
- https://sparse.tamu.edu/MM/Boeing/pwtk.tar.gz

The SuiteSparse Matrix Collection also have other matrices that you can try out the SpMV and SDDMM examples with. We didn't include them in this repository for potential copyright reasons. 

The third one is a tensor that we assembled ourselves from [this dataset](http://socialnetworks.mpi-sws.org/data-wosn2009.html). Again we didn't include it in this repository for copyright reasons. However, you can try out the MTTKRP example with tensors from the [FROSTT Tensor Collection](http://frostt.io/tensors/) instead (see [this](http://frostt.io/tensors/nell-2/) for instance).

**Comment by stephenchouca** [comment]
@fredrikbk I've updated the documentations accordingly.
