### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by SebSchr** [tensor-compiler/taco#133]
Hello guys,

I am trying to use taco to evaluate the right-hand-sight of a system of ODEs. As this entails looping to  propagate the system, I encountered the odd behaviour that my program uses up all the memory if it iterates long enough. As my test systems only were in the order of 10 equations, none of the involved tensors should use up 10s of gigabytes of my memory. I tested it with a simple working example code without all the surrounding code and it still happens. I am a bit puzzled what could cause this and wanted to pass this along to see if you guys have an idea how to fix this.

    #include <taco.h>                                // tensor algebra compiler
    
    using namespace taco;
    
    int main()
    {
        Tensor<double> id({10,10},Format(Sparse));
        Tensor<double> x({10},Format(Dense));
        Tensor<double> y({10},Format(Dense));
    
        /// initialize tensors
        for (int i = 0; i < 10; i++)
            x.insert({i}, 1);
        x.pack();
     
        for (int i = 0; i < 10; i++)
            id.insert({i,i}, 1);
        id.pack();
    
        IndexVar i,j;
        y(i) = T(i,j)*x(j);
        y.compile();
    
        for(int i{0}; i < 1e9; i++)
            {
                y.assemble();
                y.compute();
            }
        return 0;
    }

**Comment by fredrikbk** [comment]
The `taco_tensor_t` struct was never deleted. I changed so it's deleted in 25107fb. Hope it works for you now! :)
