### ISSUE TITLE
assembleCompute() capability not present

### ISSUE THREAD

**Issue by nitish2112** [tensor-compiler/taco#136]
Hi Fred,

The TACO technical report  [link](https://dspace.mit.edu/bitstream/handle/1721.1/107013/MIT-CSAIL-TR-2017-003.pdf) section 6 talks about assembleCompute( ) method that can merge the assemble and compute functions, but it doesn't seem to be implemented in taco repository?

Thanks,

Best,
Nitish

**Comment by fredrikbk** [comment]
Hi Nitish,

(We have a full paper that is much nicer to read than the technical report at https://dl.acm.org/citation.cfm?id=3133901.)

Yes, our code generation machinery should support this, but as you point out we haven't exposed it in the tensor API or tested it. This is an omission that we have to address soon. I'll do it after I fix the sparse matrix multiplication, but first I have to fix a small bug with compute code emission.

Appreciate the reports!
Fred

**Comment by fredrikbk** [comment]
@stephenchouca, perhaps you can implement this once your master thesis is done?

**Comment by stephenchouca** [comment]
Actually we already have something like that implemented. The `compile` method takes as argument a Boolean flag that controls whether or not the generated compute kernel does assembly as well, so if you call `A.compile(true)` then you should be able to just call `A.compute()` without having to explicitly call `A.assemble()` beforehand.

I haven't tested this very extensively though, so there might still be some outstanding bugs; please let me know if there is any. This interface also isn't exactly the cleanest, so we might want to redesign it at some point.

**Comment by nitish2112** [comment]
I tried the following program:
`
#include <iostream>
#include "taco.h"

using namespace taco;

int main(int argc, char* argv[]) {
  // Create formats
  Format csf0({Sparse, Sparse}, {0,1});
  Format csf1({Sparse, Sparse}, {1,0});
  Format csr({Dense,Sparse}, {0,1});
  Format csc({Dense,Sparse}, {1,0});
  Format  sv({Sparse});

  // Create tensors
  Tensor<double> Y({4,4},   csf0);
  Tensor<double> A({4,3},   csf0);
  Tensor<double> B({3,4},   csf1);
  Tensor<double> C({4,4},   csf0);

  // Insert data into B and c
  A.insert({0,0}, 1.0);
  A.insert({1,2}, 2.0);
  A.insert({1,1}, 3.0);
  B.insert({0,0}, 1.0);
  B.insert({1,2}, 2.0);
  B.insert({1,1}, 3.0);
  C.insert({0,0}, 1.0);
  C.insert({1,2}, 2.0);
  C.insert({1,1}, 3.0);

  // Pack data as described by the formats
  A.pack();
  B.pack();
  C.pack();

  // Form a tensor-vector multiplication expression
  IndexVar i, j, k;
  Y(i, j) = (A(i,k) * B(k,j)) + C(i,j);

  // Compile the expression
  Y.compile(true);

  // Assemble A's indices and numerically compute the result
  // Y.assemble();
  Y.compute();

  std::cout << Y << std::endl;
}
`

This also produces both the assemble() and compute() functions. The thing I was asking was is there a way to merge to the codes for the generated compute( ) and assemble( ) functions.

Thanks,
Nitish
