### ISSUE TITLE
cmake build error

### ISSUE THREAD

**Issue by lijiansong** [tensor-compiler/taco#143]
CMake Error at tools/CMakeLists.txt:7 (SET_TARGET_PROPERTIES):
  SET_TARGET_PROPERTIES called with incorrect number of arguments

**Comment by fredrikbk** [comment]
Hi, thanks for the report! What environment (OS, CMake version) are you using?

**Comment by lijiansong** [comment]
@fredrikbk 
Linux OS:
`Linux version 3.10.0-514.6.1.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Wed Jan 18 13:06:36 UTC 2017`

cmake version:
`3.10.0`
