### ISSUE TITLE
regarding tensor format

### ISSUE THREAD

**Issue by eric-haibin-lin** [tensor-compiler/taco#155]
A few questions regarding tensor format in taco:
- Does the CSR format in taco support duplicated entries? In scipy, duplicate entries are added up together
- For CSR, are the indices of non-zeros in each row sorted in an ascending order, or it doesn't matter? In scipy, there's an option to sort_indices

**Comment by fredrikbk** [comment]
Hi @eric-haibin-lin, I'm guessing scipy adds the entries together when the matrix is packed?  This is the way taco does this too, however:

- @stephenchouca has been working on an extension to taco that will also let us compute with tensors that have duplicates in them.
- I believe @tmarkovich is working on an improved data import interface with more flexibility.

**Comment by eric-haibin-lin** [comment]
Yes, scipy adds the entries together. For the second question, I’m just wondering if taco requires sorted indices and takes advantage of that during computation.

**Comment by stephenchouca** [comment]
Currently taco does require sorted indices. The extension we've been working on will also support computing directly with unsorted indices, though we will still be able to generate more optimized code for operands with sorted indices.

**Comment by eric-haibin-lin** [comment]
Thanks for the explanation!
