### ISSUE TITLE
Compilation fails on master

### ISSUE THREAD

**Issue by Ravenwater** [tensor-compiler/taco#156]
In addition to lots of warnings, I am running into a compilation error for simplify.cpp in the ir.h.

[ 29%] Building CXX object src/CMakeFiles/taco.dir/lower/merge_lattice.cpp.o
[ 30%] Building CXX object src/CMakeFiles/taco.dir/ir/simplify.cpp.o
In file included from /home/stillwater/dev/clones/taco/src/ir/simplify.cpp:6:0:
/home/stillwater/dev/clones/taco/include/taco/ir/ir.h: In function ‘const E* taco::ir::to(taco::ir::Expr)’:
/home/stillwater/dev/clones/taco/include/taco/ir/ir.h:672:35: error: must #include <typeinfo> before using typeid
       "Cannot convert " << typeid(e).name() << " to " <<typeid(E).name();
                                   ^
/home/stillwater/dev/clones/taco/include/taco/ir/ir.h:672:65: error: must #include <typeinfo> before using typeid
       "Cannot convert " << typeid(e).name() << " to " <<typeid(E).name();
                                                                 ^
/home/stillwater/dev/clones/taco/include/taco/ir/ir.h: In function ‘const S* taco::ir::to(taco::ir::Stmt)’:
/home/stillwater/dev/clones/taco/include/taco/ir/ir.h:679:35: error: must #include <typeinfo> before using typeid
       "Cannot convert " << typeid(s).name() << " to " <<typeid(S).name();
                                   ^
/home/stillwater/dev/clones/taco/include/taco/ir/ir.h:679:65: error: must #include <typeinfo> before using typeid
       "Cannot convert " << typeid(s).name() << " to " <<typeid(S).name();
                                                                 ^
src/CMakeFiles/taco.dir/build.make:662: recipe for target 'src/CMakeFiles/taco.dir/ir/simplify.cpp.o' failed
make[2]: *** [src/CMakeFiles/taco.dir/ir/simplify.cpp.o] Error 1
CMakeFiles/Makefile2:117: recipe for target 'src/CMakeFiles/taco.dir/all' failed
make[1]: *** [src/CMakeFiles/taco.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by stephenchouca** [comment]
It looks like a problem with missing headers. Can you try the latest commit and see if that resolves the issue? As for the other compiler warnings, I can take a look if you post them here and/or let me know what compiler you're using.

**Comment by Ravenwater** [comment]
Latest commit has new problems:
[ 27%] Building CXX object src/CMakeFiles/taco.dir/ir/ir.cpp.o
/home/stillwater/dev/clones/taco/src/ir/ir.cpp: In static member function ‘static taco::ir::Expr taco::ir::Li                                        teral::zero(taco::Datatype)’:
/home/stillwater/dev/clones/taco/src/ir/ir.cpp:96:39: error: call of overloaded ‘make(uint64_t)’ is ambiguous
       zero = Literal::make((uint64_t)0);
                                       ^
/home/stillwater/dev/clones/taco/src/ir/ir.cpp:31:6: note: candidate: static taco::ir::Expr taco::ir::Literal                                        ::make(bool)
 Expr Literal::make(bool val) {
      ^
/home/stillwater/dev/clones/taco/src/ir/ir.cpp:38:6: note: candidate: static taco::ir::Expr taco::ir::Literal                                        ::make(int)
 Expr Literal::make(int val) {
.....

I am using g++ 5.4.0:
stillwater@sw-11:~/dev/clones/taco/build$ g++ --version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.

**Comment by Ravenwater** [comment]
Trying on a newer system: Ubuntu 18.04, g++ 7.3.0, ir.cpp still has issues:

```
[ 34%] Building CXX object src/CMakeFiles/taco.dir/ir/ir.cpp.o
/mnt/c/Users/tomtz/Documents/dev/clones/taco/src/ir/ir.cpp: In static member function â€˜static taco::ir::Expr taco::ir::Literal::zero(taco::Datatype)â€™:
/mnt/c/Users/tomtz/Documents/dev/clones/taco/src/ir/ir.cpp:96:39: error: call of overloaded â€˜make(uint64_t)â€™ is ambiguous
       zero = Literal::make((uint64_t)0);
                                       ^
/mnt/c/Users/tomtz/Documents/dev/clones/taco/src/ir/ir.cpp:31:6: note: candidate: static taco::ir::Expr taco::ir::Literal::make(bool)
 Expr Literal::make(bool val) {
      ^~~~~~~
/mnt/c/Users/tomtz/Documents/dev/clones/taco/src/ir/ir.cpp:38:6: note: candidate: static taco::ir::Expr taco::ir::Literal::make(int)
 Expr Literal::make(int val) {
      ^~~~~~~
/mnt/c/Users/tomtz/Documents/dev/clones/taco/src/ir/ir.cpp:45:6: note: candidate: static taco::ir::Expr taco::ir::Literal::make(uint32_t)
 Expr Literal::make(uint32_t val) {
      ^~~~~~~
/mnt/c/Users/tomtz/Documents/dev/clones/taco/src/ir/ir.cpp:52:6: note: candidate: static taco::ir::Expr taco::ir::Literal::make(long long int)
 Expr Literal::make(long long val) {
      ^~~~~~~
/mnt/c/Users/tomtz/Documents/dev/clones/taco/src/ir/ir.cpp:59:6: note: candidate: static taco::ir::Expr taco::ir::Literal::make(long long unsigned int)
 Expr Literal::make(unsigned long long val) {
      ^~~~~~~
/mnt/c/Users/tomtz/Documents/dev/clones/taco/src/ir/ir.cpp:66:6: note: candidate: static taco::ir::Expr taco::ir::Literal::make(std::complex<double>)
 Expr Literal::make(std::complex<double> val) {
      ^~~~~~~
/mnt/c/Users/tomtz/Documents/dev/clones/taco/src/ir/ir.cpp:73:6: note: candidate: static taco::ir::Expr taco::ir::Literal::make(double)
 Expr Literal::make(double val) {
      ^~~~~~~
/mnt/c/Users/tomtz/Documents/dev/clones/taco/src/ir/ir.cpp:111:38: error: call of overloaded â€˜make(int64_t)â€™ is ambiguous
       zero = Literal::make((int64_t)0);
                                      ^
/mnt/c/Users/tomtz/Documents/dev/clones/taco/src/ir/ir.cpp:31:6: note: candidate: static taco::ir::Expr taco::ir::Literal::make(bool)
 Expr Literal::make(bool val) {
      ^~~~~~~
/mnt/c/Users/tomtz/Documents/dev/clones/taco/src/ir/ir.cpp:38:6: note: candidate: static taco::ir::Expr taco::ir::Literal::make(int)
 Expr Literal::make(int val) {
      ^~~~~~~
/mnt/c/Users/tomtz/Documents/dev/clones/taco/src/ir/ir.cpp:45:6: note: candidate: static taco::ir::Expr taco::ir::Literal::make(uint32_t)
 Expr Literal::make(uint32_t val) {
      ^~~~~~~
/mnt/c/Users/tomtz/Documents/dev/clones/taco/src/ir/ir.cpp:52:6: note: candidate: static taco::ir::Expr taco::ir::Literal::make(long long int)
 Expr Literal::make(long long val) {
      ^~~~~~~
/mnt/c/Users/tomtz/Documents/dev/clones/taco/src/ir/ir.cpp:59:6: note: candidate: static taco::ir::Expr taco::ir::Literal::make(long long unsigned int)
 Expr Literal::make(unsigned long long val) {
      ^~~~~~~
/mnt/c/Users/tomtz/Documents/dev/clones/taco/src/ir/ir.cpp:66:6: note: candidate: static taco::ir::Expr taco::ir::Literal::make(std::complex<double>)
 Expr Literal::make(std::complex<double> val) {
      ^~~~~~~
/mnt/c/Users/tomtz/Documents/dev/clones/taco/src/ir/ir.cpp:73:6: note: candidate: static taco::ir::Expr taco::ir::Literal::make(double)
 Expr Literal::make(double val) {
      ^~~~~~~
src/CMakeFiles/taco.dir/build.make:662: recipe for target 'src/CMakeFiles/taco.dir/ir/ir.cpp.o' failed
make[3]: *** [src/CMakeFiles/taco.dir/ir/ir.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [src/CMakeFiles/taco.dir/all] Error 2
make[1]: *** [test/CMakeFiles/taco-test.dir/rule] Error 2
make: *** [taco-test] Error 2
```

did I catch a bad master check-in?

**Comment by stephenchouca** [comment]
It seems the problem is that on MacOS (which most of us use for development) `(u)int64_t` is a typedef of `(unsigned) long long int`, while on Linux it is a typedef of `(unsigned) long int` instead. 48fc577 fixes the issue by changing `Literal::make` to take only fixed-width integers as input and should compile and run on both Linux and MacOS. Let me know if you encounter any more compilation errors.

**Comment by Ravenwater** [comment]
Awesome, thank you very much for the fix, I am now able to build the tool set on Linux and WSL. From the CMakeLists.txt it is clear that you are not supporting MSVC as all the compiler flags are gcc specific. Any interest in me trying to add Windows/MSVC support to taco? We are working on tensor processor hardware and your research is a perfect fit for the front-end of our tensor processor, but Apple products are not very open to custom hardware acceleration innovations.

Again, thank you for getting master build green again.

**Comment by stephenchouca** [comment]
That would certainly be very cool I think. Any thoughts on this @fredrikbk?

**Comment by fredrikbk** [comment]
@Ravenwater Windows compilation would be great. Perhaps you'd be interested in giving it a shot if taco works out for you on Linux? @shoaibkamil I think you had some thoughts on windows compilation a while ago?

I also think taco can be a great fit for tensor hardware. I'm rewriting our lowering machinery and I'm aiming at making the new iteration more of a lowering construction toolbox so that different pieces can be hijacked to target different accelerator features. We'll eventually write up a paper on it to share.

**Comment by Ravenwater** [comment]
Yep, I am definitely interested to get my hands dirty in this piece of code, and since my working environment is Windows that would all be par for the course. @shoaibkamil, please ping me so that I don't reinvent the wheel in the wrong image.

Very interesting to hear about the lowering toolbox, that definitely would make tensor hardware easier to innovate around. I'll be looking forward to that paper.

**Comment by fredrikbk** [comment]
I'll do most development on a branch and try to test with GCC linux when I move it to master. With that we should avoid most of the Linux breakage.

I've also opened #157 on continuous testing so that we can get rid of these problems.

**Comment by fredrikbk** [comment]
@Ravenwater if I remember correctly, then @shoaibkamil insight was that Windows is moving towards disallowing executing arbitrary memory, which rules out LLVM online backends. Our system, however, calls a system compiler followed by dlopen (or similar) and should therefore still work on Windows. @shoaibkamil is that correct?

I'll keep you updated about the paper. We're thinking of writing it about requirements of sparse tensor accelerators from the point of view of what we can most efficiently compile.

**Comment by shoaibkamil** [comment]
Yes, that’s correct: on Posix-y systems, we write out the file and call the system compiler to generate a shared library that we subsequently dlopen().

On Windows, we should be able to call cl.exe and then use LoadLibrary or similar to load the resulting compiled shared library.

@ravenwater, let me know if you need guidance on what to modify within taco.

**Comment by Ravenwater** [comment]
@shoaibkamil I will need to get more familiarity with the taco code base before I'll attempt a modification. Once I feel that I understand how the system is put together, I'll definitely give you a ping.

I am keenly interested in the IR and how we could execute that IR directly in our tensor processor. The reason for offering to create a Windows port is because of our dev environment being Windows/Linux.
