### ISSUE TITLE
Scalar multiplication with changing scalar

### ISSUE THREAD

**Issue by LucaCerina** [tensor-compiler/taco#163]
Hello everyone,
I am testing taco on a sparse vector times scalar program, but I am having some issue in the flow to follow.

The equation is in the form
y(i) = A(i) * c() or y(i) = A(i)*x
both works fine and I obtain the correct result. However, I don't understand how to change the value of the scalar to perform a new computation.
Calling y.compile() again crashes the program, but calling only assemble and compute does not change the computation result.
Can you help me?

**Comment by fredrikbk** [comment]
Hi, with the current frontend API you should be able to call something like `x.getStorage().getValues()[0] = 42;` to change the value of `x`. We're working towards simplifying these APIs.

**Comment by LucaCerina** [comment]
Worked flawlessly with c(), does not work with a double constant (not a Tensor) 'x' because of course it does not provide the getStorage method.
I guess that the Storage part of the code could be documented better in the docs.

Thank you

**Comment by fredrikbk** [comment]
@LucaCerina you are right, it absolutely should be documented better. The reason why it's not is that it's still in flux. We've focused on the code generation machinery and want to circle around to clean up the storage system.

Glad it works for you though!
