### ISSUE TITLE
taco assembly generate useless code

### ISSUE THREAD

**Issue by zhezhouzz** [tensor-compiler/taco#164]
version: master branch(commit 6a75daccc1844db69d5f93f0bc4520c5f27b7b5a)
run in commandline: `taco "y(i)=A(i,j)*x(j)" -f=y:d:0 -f=A:dd:0,1 -f=x:d:0 -write-source=taco_kernel.c -write-compute=taco_compute.c -write-assembly=taco_assembly.c`
generate: 
`// Generated by the Tensor Algebra Compiler (tensor-compiler.org)
for (int32_t iA = 0; iA < A1_dimension; iA++) {
  for (int32_t jA = 0; jA < A2_dimension; jA++) {
    int32_t pA2 = iA * A2_dimension + jA;
  }
}

allocate y_vals[y1_dimension]
y_vals_size = y1_dimension;
`
here is the whole output:
[taco_output.zip](https://github.com/tensor-compiler/taco/files/2259735/taco_output.zip)

Of cause, this loop(int32_t pA2 = iA * A2_dimension + jA;) is useless. The online taco(http://tensor-compiler.org/codegen.html) however generate the right code:

`// Generated by the Tensor Algebra Compiler (tensor-compiler.org)
allocate y_vals[y1_size]`

**Comment by fredrikbk** [comment]
The code generator in taco was recently extended with features to eventually support more formats.  I don't know what's wrong in this case, but It looks like @stephenchouca will take a look.  For your information, I'm rewriting this code generator yet again to be simpler and more robust.

**Comment by stephenchouca** [comment]
Previously the code generator was hard-coded to not emit the assembly loops when the output is fully dense, though you'd actually get a similar problem with formats like `(sparse,dense)`. I had some ideas for a hopefully more robust fix, which I can look into it more after @fredrikbk's done with the code generator rewrite.
