### ISSUE TITLE
USing workspaces (for example, for SPMM)

### ISSUE THREAD

**Issue by srobertp** [tensor-compiler/taco#184]
Hi, I am attempting to recreate the spmm with workspace example in order to better understand how to use the TACO compiler.  I have tried a number of different ways and have not been able to get it to generate the workspace formulation.

I will give example of three ways I have tried, I hope you can advise on a better way :)

1)  I observe that the method and API described in the workspace paper is no longer part of this library:

```
Format csr({Dense,Sparse});
Format  dv({Dense});

Tensor<double> B = read("B.mtx", csr);
Tensor<double> C = read("C.mtx", csr);
Tensor<double> A({B.getDimension(0),C.getDimension(1)}, csr);

IndexVar i, j, k;
IndexExpr mul = B(i,k)*C(k,j);
IndexStmt matmul = (A(i,j) = sum(k,mul));
matmul.reorder(k,j); // does not exist in APIS

IndexVar jc,jp;
Type vec(A.getComponentType(), {B.getDimension(1)});
TensorVar w(vec, dv);
matmul.precompute(mul, {{j,jc,jp}}, w);  // does not exist in APIs

A.compile();
A.assemble();
A.compute();
write("A.mtx", A);
```

2)  I did find that you have created some new Transformation objects called Reorder and Precompute and so I thought that might work, but it still does the inner product method:

```
// add to includes
#include "taco/index_notation/transformations.h"

// replace matmul.reorder(k,j); with 
Reorder reorder(k,j);
matmul = reorder.apply(matmul);

// replace matmul.precompute(mul, {{j,jc,jp}}, w);
Precompute precompute(mul, j, jp, w);
matmul = precompute.apply(matmul);
```

3)  I looked into the concrete index notation and worked out that it should look something like:

```
    IndexStmt matmul = forall(i,
                                forall(k,
                                        where(forall(j,
                                                    A(i,j)=w(j)
                                                    ),
                                              forall(j,
                                                    w(j) += B(i,k)*C(k,j)
                                                    )
                                             )
                                      )
                             );
```
Do we need something that sets w(j) = 0 on copy out into A(i,j)?  or is that built into the where formulation ?

Compiling the above with this matmul statement instead of the other stuff gives the following error:

> Compiler bug at <path to taco lib>/taco/src/lower/merge_lattice_old.cpp:326 in make
> Please report it to developers
>  Condition failed: lattice.getSize() > 0
>  Every merge lattice should have at least one merge point

I appreciate any help you can give toward this.  

PS  Have you considered ways of having openmp parallelism (#pragma omp parallel for ) for the outer most loop (forall(i, ...)?  This would require a large global workspace array, w_global, of size num_omp_threads * C.dimension(1),  then local workspaces arrays are initiated as w_loc = w_glob + thread_num * C.dimension(1) and you scatter into w_loc[k]  instead of w_global[k] ) for each thread?  Or alternatively, you could have a thread local storage type creation of workspace on demand for each thread which would handle more general cases where the number of threads is not hard coded anywhere.  The assembly routine would have to create the row pointer data structure of output matrix so that each row's colind and values can independently be filled in during the execute phase.

**Comment by fredrikbk** [comment]
Hi @srobertp,

Thank you for bringing this up.  We are still getting the new workspace and format features into the master branch, as we are rewriting the internal compiler machinery.  It will take us some time to put everything together with limited resources.  I believe we'll have the new compiler machinery and these optimizations implemented within the next two months.

The initialization of workspaces (w=0) are built into the formulation and will be emitted automatically with the new machinery.

Separately we've also started to look into a full scheduling language (@RSenApps) that will include commands such as `parallelize` and `split` (see Halide) for sparse computations.  Using the `parallelize` primitive together with workspaces means there will have to be one workspace per thread in many cases, as you suggested.  I hope we'll get a chance to talk about this more on Saturday!
