### ISSUE TITLE
max and rescale

### ISSUE THREAD

**Issue by jcrbloch** [tensor-compiler/taco#191]
Two questions:
a) Is there a way to determine the maximum value of all entries of a tensor?
b) Is there a way to rescale the entire tensor with that value?

**Comment by fredrikbk** [comment]
In the current version, you have to iterate over the components in the tensor with a `foreach` loop to find the max.  You can then multiply the tensor by that value using index notation, e.g. `A(i,j,k) = alpha * B(i,j,k)`.  This statement is out-of-place and copies your tensor.  We don't have `*=` overloaded yet (@oicirtap).  In the next version, planned for this summer, we will support in-place `*=` and also hope to support a way to apply a function to the tensor non-zero values.

**Comment by jcrbloch** [comment]
Dear Frederik,

Thanks for you very quick answer. I did not know that C++ had a foreach construct. As I want to have a routine that works for any tensor order, I implemented the max-function as following: (it computes the maximum of the absolute values, as this is what I need)

double max(Tensor<double> &T) 
{ 
	Array content=T.getStorage().getValues();
	double *data = (double*)content.getData();

 	double maxt=0;  	
	for (size_t i=0; i<content.getSize();i++)
		maxt = std::max(maxt,abs(data[i]));
	return maxt; 
}

Does that look okay?

Thanks,
Jacques

---
Dr. Jacques C.R. Bloch
Institute for Theoretical Physics
University of Regensburg
93040 Regensburg, Germany
tel: +49 941 943-2018
fax: +49 941 943-3887
email: jacques.bloch@ur.de
web: https://homepages.uni-regensburg.de/~blj05290

**Comment by jcrbloch** [comment]
Could you tell me how the foreach loop would look like? What are the start and end iterators of the tensors? I just startet looking at taco last night, so I am pretty new to it. As the documentation is sparse I am looking through the source to try and locate which routines could be useful to me.

Thanks,
Jacques

---
Dr. Jacques C.R. Bloch
Institute for Theoretical Physics
University of Regensburg
93040 Regensburg, Germany
tel: +49 941 943-2018
fax: +49 941 943-3887
email: jacques.bloch@ur.de
web: https://homepages.uni-regensburg.de/~blj05290

**Comment by jcrbloch** [comment]
To avoid having two copies of the tensor when rescaling it, I implemented the rescaling like this:

void rescale(Tensor<double> &T, double s) 
{ 
	Array content=T.getStorage().getValues();
	double *data = (double*)content.getData();

	for (size_t i=0; i<content.getSize(); i++)
		data[i] /= s;
	cout << "rescaled\n"; 
}

Saving storage is extremely important in my application, so I want to avoid unnecessary copies.

Thanks,
Jacques

**Comment by fredrikbk** [comment]
That does look okay and fairly fast.  By accessing the values memory directly, however, you do make it less portable to new formats. This will work for any combination of dense and compressed, however, it will not necessarily work for future formats that may store value memory discontiguous with holes that are not initialized.  That is pretty far-fetched at this point though and it may be acceptable to just always initialize the whole value array so that this kind of code works  (@stephenchouca ?).

An alternative is to use a foreach loop over the tensor, which would iterate over its non-zeros, but that would be much slower than what you have as it would iterate over index structures and return coordinates as well as values. The following should work (but I didn't test it):
```
foreach (auto component : mytensor) {
  ...
}
```

**Comment by fredrikbk** [comment]
For your application I would go with what you've written above as its faster and, for elementwise operations like yours, correct for formats we currently support.

**Comment by oicirtap** [comment]
An example of iterating over non-zeros of the tensor can also be found here:

https://github.com/tensor-compiler/taco/blob/6a75daccc1844db69d5f93f0bc4520c5f27b7b5a/src/storage/file_io_tns.cpp#L104

As for scaling the vector, currently your proposed solution is probably the best way to do so. Iterating over the values of a tensor currently does not allow you to modify them within the tensor as far as I understand.

**Comment by jcrbloch** [comment]
Thanks for your replies and comments!
