### ISSUE TITLE
Problem with reductions

### ISSUE THREAD

**Issue by jcrbloch** [tensor-compiler/taco#196]
Somehow most of my reductions on higher order tensors are just wrong. Are there some unwritten rules about the order of indices in input and output tensors? I have for example something like:
`b(y2f,i,y1b,z1f,z1b) = U1(y1f,y2f) * T(i,y1f,y1b,z1f,z1b);
b.evaluate();`
The tensor U1 is completely zero, up to a single 1.0. This means that b should very much look like T.
This is not what comes out of the calculation, as one of the components of b comes out to be 10^231. The results are:

> T (2x2x2x2x2) ({dense},{dense},{dense},{dense},{dense}; 0,1,2,3,4):
> dense (0):
>   [2]
> dense (1):
>   [2]
> dense (2):
>   [2]
> dense (3):
>   [2]
> dense (4):
>   [2]
> [1, 0, 0, 0.218635, 0, 0.218635, 0.218635, 0, 0, 0.218635, 0.218635, 0, 0.218635, 0, 0, 0.0478013, 0, 0.218635, 0.218635, 0, 0.218635, 0, 0, 0.0478013, 0.218635, 0, 0, 0.0478013, 0, 0.0478013, 0.0478013, 0]

> U1 (2x2) ({dense},{dense}; 0,1):
> dense (0):
>   [2]
> dense (1):
>   [2]
> [1, 0, 0, 0]

> b (2x2x2x2x2) ({dense},{dense},{dense},{dense},{dense}; 0,1,2,3,4):
> dense (0):
>   [2]
> dense (1):
>   [2]
> dense (2):
>   [2]
> dense (3):
>   [2]
> dense (4):
>   [2]
> [1, -1.49458e-154, -1.72723e-77, -1.72723e-77, 3.45846e-323, 0, 0, 0, 0, 0, -1.72723e-77, -1.72723e-77, 6.94675e-310, 6.94675e-310, -1.72723e-77, 9.77812e-309, -1.72723e-77, 3.11109e+231, -1.72723e-77, 6.94675e-310, 4.94066e-324, 4.94066e-324, 2.23854e-314, 2.122e-314, 6.94675e-310, 0, 6.94675e-310, 6.94675e-310, 6.94675e-310, 4.94066e-324, 2.47033e-322, 6.94675e-310]

**Comment by Infinoid** [comment]
Here's a reproducer based on your description: https://gist.github.com/Infinoid/2d8fa36f89c6e5f595241769d73cf4e4

The current taco (master branch) seems to generate reasonable results.  Here's what I get:

```
b (2x2x2x2x2) ({dense},{dense},{dense},{dense},{dense}; 0,1,2,3,4):
dense (0): 
  [2]
dense (1): 
  [2]
dense (2): 
  [2]
dense (3): 
  [2]
dense (4): 
  [2]
[1, 0, 0, 0.218635, 0, 0.218635, 0.218635, 0, 0, 0.218635, 0.218635, 0, 0.218635, 0, 0, 0.0478013, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
```
