### ISSUE TITLE
-print-nocolor should be -nocolor or vice versa

### ISSUE THREAD

**Issue by drhagen** [tensor-compiler/taco#198]
The help for the taco command line tool says that the `-print-nocolor` should disable color when printing. However, this flag is not recognized and the command errors. Digging into the source code reveals that the flag is actually called `-nocolor`, which works as expected. Is the help correct or is the behavior correct?

**Comment by drhagen** [comment]
Also, `-nocolor` suppresses only a tiny fraction of the color that is typically printed.

**Comment by stephenchouca** [comment]
My understanding is that `-print-nocolor` is the correct flag; that should be fixed with the latest commit. `-print-nocolor` should also now fully (as opposed to just partially) disable coloring.
