### ISSUE TITLE
reduction using the sum of IndexVar

### ISSUE THREAD

**Issue by dongxiao92** [tensor-compiler/taco#205]
Thanks for your excellent work with taco. I'm working on using taco to achieve convolution operation but encountering a problem. 
When I do the reduction across the channel and convolution filter dimensions, the compiler reports error of 
"no match for ‘operator+’ (operand types are ‘taco::IndexVar’ and ‘taco::IndexVar’)
   output(oh, ow, ok) = input(oh+kh, ow+kw, ic)*weight(ok, ic, kh, kw);"

The code is listed below.
```
         IndexVar oh, ow, ok, ic, kh, kw;
         output(oh, ow, ok) = input(oh+kh, ow+kw, ic)*weight(ok, ic, kh, kw);
```

output, input and weight are all Tensors.  I assume the error means I cannot describe the reduction in this way. So does taco supports this kind of reduction? If do, how should I describe the computation?

**Comment by oicirtap** [comment]
Just as you pointed out, taco does not support notation of addition of `IndexVar` objects. In taco, IndexVars are used to represent iteration over a tensor dimension, and taco requires the dimension of each tensor to be mapped to a single IndexVar. IndexVar addition is therefore not defined and this is why you are not able to compile your expression.

I am personally not very familiar with the notation you are trying to use to express your convolution operation, but maybe augmenting the input tensor with additional dimensions can give you more flexibility on what you are trying to express? Could you describe a bit of how the different dimensions of input and weight interact with each other?

**Comment by dongxiao92** [comment]
> Just as you pointed out, taco does not support notation of addition of `IndexVar` objects. In taco, IndexVars are used to represent iteration over a tensor dimension, and taco requires the dimension of each tensor to be mapped to a single IndexVar. IndexVar addition is therefore not defined and this is why you are not able to compile your expression.
> 
> I am personally not very familiar with the notation you are trying to use to express your convolution operation, but maybe augmenting the input tensor with additional dimensions can give you more flexibility on what you are trying to express? Could you describe a bit of how the different dimensions of input and weight interact with each other?

Thanks for you reply. 
2D convolution requires two input tensors,the  3d tensor **image** and the 4d tensor **weight**, and generates a 3d tensor **output**. For each location**(h, w, k)** of the output tensor, the value is the 'inner-product' between the unrolled k'th slice of the **weight** tensor and a block of the **image** tensor. The block's location is determined by the location of the output, **(h,w)**, and the spatial size of the block is defined by the size of the weight tensor. The math expression is shown as:
` output(h, w, k) = imaget(h+kh, w+kw, c)*weight(k, c, kh, kw)`
You can see for each location of the output, we are doing reduction along **c**, **kh**, and **kw** dimensions. If written in C-style code, it will be like this:
```
for h in (0, height)
  for w in (0, width)
    for k in (0, kernel_number)
        output[h, w, k] = 0
        for kh in (0, kernel_height)
          for kw in (0, kernel_width)
            for c in (0, channel_number)
              output[h, w, k] += image[h+kh, w+kw, c]*weight[k, kh, kh, c]
```

**Comment by oicirtap** [comment]
To the best of my knowledge, taco is not currently capable of compiling convolution operations as the one you described, but it seems like an interesting possibility to explore. Maybe @fredrikbk has better insight about if there exists some compiler trick that can be used to simulate the operation though.
