### ISSUE TITLE
How to use kernels?

### ISSUE THREAD

**Issue by nt1tov** [tensor-compiler/taco#218]
I've generated some kernels.h, how can I add it to my app without running taco compile every time?

**Comment by fredrikbk** [comment]
Just include the directory it is in to your build system and include the file in your application.

The only issue is that our code generator tools do not yet produce code to pack tensors into storage formats or to iterate over them, etc.  This code will be generated by the [new lowering machinery](https://github.com/tensor-compiler/taco/projects/3) and then the taco command-line and online tools will generate both the kernel and packing/unpacking/iteration helper functions.

**Comment by nt1tov** [comment]
I dont undestand how I can use, just for example, Kernel for MSpM kernel and MM kernel in one program for different dimensions?
May be You can show examples of including to a simple program a kernel?

**Comment by nt1tov** [comment]
> Just include the directory it is in to your build system and include the file in your application.
> 
> The only issue is that our code generator tools do not yet produce code to pack tensors into storage formats or to iterate over them, etc. This code will be generated by the [new lowering machinery](https://github.com/tensor-compiler/taco/projects/3) and then the taco command-line and online tools will generate both the kernel and packing/unpacking/iteration helper functions.

but what can do generated code?
Does it use hardcoded values & dimensions?Or only algebra equation?
Can you send simple code for example how generated kernel works in app?

**Comment by fredrikbk** [comment]
Answered in other thread
