### ISSUE TITLE
Any ideas How I can use generated kernel?

### ISSUE THREAD

**Issue by nt1tov** [tensor-compiler/taco#229]
http://tensor-compiler.org/
I have A(i,j) = B(i,k) * C(k,j) kernel for this expression
How I can init this tensors without extra code generating and use this code for my own project without taco library?

I have read a lot of papers and github issues but nowhere I've found solutions and guides HOW I use the taco_kernel.c??

`﻿// Generated by the Tensor Algebra Compiler (tensor-compiler.org)
// taco "A(i,j)=B(i,k)*C(k,j)" -f=A:dd:0,1 -f=B:dd:0,1 -f=C:ss:0,1 -write-source=taco_kernel.c -write-compute=taco_compute.c -write-assembly=taco_assembly.c
#ifndef TACO_C_HEADERS
#define TACO_C_HEADERS
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <math.h>
#include <complex.h>
#define TACO_MIN(_a,_b) ((_a) < (_b) ? (_a) : (_b))
#define TACO_MAX(_a,_b) ((_a) > (_b) ? (_a) : (_b))
#ifndef TACO_TENSOR_T_DEFINED
#define TACO_TENSOR_T_DEFINED
typedef enum { taco_mode_dense, taco_mode_sparse } taco_mode_t;
typedef struct {
  int32_t      order;         // tensor order (number of modes)
  int32_t*     dimensions;    // tensor dimensions
  int32_t      csize;         // component size
  int32_t*     mode_ordering; // mode storage ordering
  taco_mode_t* mode_types;    // mode storage types
  uint8_t***   indices;       // tensor index data (per mode)
  uint8_t*     vals;          // tensor values
  int32_t      vals_size;     // values array size
} taco_tensor_t;
#endif
#endif

int assemble(taco_tensor_t *A, taco_tensor_t *B, taco_tensor_t *C) {
  int A1_dimension = (int)(A->dimensions[A->mode_ordering[0]]);
  int A2_dimension = (int)(A->dimensions[A->mode_ordering[1]]);
  double* restrict A_vals = (double*)(A->vals);
  int A_vals_size = A->vals_size;
  int B1_dimension = (int)(B->dimensions[B->mode_ordering[0]]);
  int B2_dimension = (int)(B->dimensions[B->mode_ordering[1]]);
  int* restrict C1_pos = (int*)(C->indices[0][0]);
  int* restrict C1_coord = (int*)(C->indices[0][1]);
  int* restrict C2_pos = (int*)(C->indices[1][0]);
  int* restrict C2_coord = (int*)(C->indices[1][1]);

  for (int32_t iB = 0; iB < B1_dimension; iB++) {
    for (int32_t pC1 = C1_pos[0]; pC1 < C1_pos[1]; pC1++) {
      int32_t kC = C1_coord[pC1];
      int32_t pB2 = iB * B2_dimension + kC;
      for (int32_t pC2 = C2_pos[pC1]; pC2 < C2_pos[(pC1 + 1)]; pC2++) {
        int32_t jC = C2_coord[pC2];
        int32_t pA2 = iB * A2_dimension + jC;
      }
    }
  }

  A_vals = (double*)malloc(sizeof(double) * A1_dimension * A2_dimension);
  A_vals_size = A1_dimension * A2_dimension;

  A->vals = (uint8_t*)A_vals;
  A->vals_size = A_vals_size;
  return 0;
}

int compute(taco_tensor_t *A, taco_tensor_t *B, taco_tensor_t *C) {
  int A1_dimension = (int)(A->dimensions[A->mode_ordering[0]]);
  int A2_dimension = (int)(A->dimensions[A->mode_ordering[1]]);
  double* restrict A_vals = (double*)(A->vals);
  int B1_dimension = (int)(B->dimensions[B->mode_ordering[0]]);
  int B2_dimension = (int)(B->dimensions[B->mode_ordering[1]]);
  double* restrict B_vals = (double*)(B->vals);
  int* restrict C1_pos = (int*)(C->indices[0][0]);
  int* restrict C1_coord = (int*)(C->indices[0][1]);
  int* restrict C2_pos = (int*)(C->indices[1][0]);
  int* restrict C2_coord = (int*)(C->indices[1][1]);
  double* restrict C_vals = (double*)(C->vals);

  #pragma omp parallel for
  for (int32_t pA = 0; pA < A1_dimension * A2_dimension; pA++) {
    A_vals[pA] = 0.0;
  }
  #pragma omp parallel for
  for (int32_t iB = 0; iB < B1_dimension; iB++) {
    for (int32_t pC1 = C1_pos[0]; pC1 < C1_pos[1]; pC1++) {
      int32_t kC = C1_coord[pC1];
      int32_t pB2 = iB * B2_dimension + kC;
      double tk = B_vals[pB2];
      for (int32_t pC2 = C2_pos[pC1]; pC2 < C2_pos[(pC1 + 1)]; pC2++) {
        int32_t jC = C2_coord[pC2];
        int32_t pA2 = iB * A2_dimension + jC;
        A_vals[pA2] = A_vals[pA2] + tk * C_vals[pC2];
      }
    }
  }
  return 0;
}`

**Comment by nt1tov** [comment]
@fredrikbk @shoaibkamil @stephenchouca please help!

**Comment by stephenchouca** [comment]
Sorry for the late reply. The example below demonstrates how you can use taco-generated code to compute with sparse tensor data structures that you've constructed without using the taco C++ library. To make the example a bit simpler and hopefully easier to understand, I've modified it slightly so that `C` is stored in the `(dense, sparse)` format (which is equivalent to the more commonly used CSR sparse matrix format, as described in [our paper](http://tensor-compiler.org/kjolstad-oopsla17-tensor-compiler.pdf)) instead of the `(sparse, sparse)` format (which is equivalent to the less common DCSR format).

Currently, the taco web tool and command-line tool do not support generating code that can convert lists of nonzero tensor components to sparse tensor data structures like CSR and DCSR. That is on our to-do list. In the meantime though, if you want to completely forgo the taco C++ library, you will either need to write code to construct the sparse tensor data structures yourself or use another library like Intel MKL that provides routines for doing the conversion (e.g., `mkl_dcsrcoo`).

```c
// Generated by the Tensor Algebra Compiler (tensor-compiler.org)
// taco "A(i,j)=B(i,k)*C(k,j)" -f=A:dd:0,1 -f=B:dd:0,1 -f=C:ds:0,1 -write-source=taco_kernel.c -write-compute=taco_compute.c -write-assembly=taco_assembly.c
#ifndef TACO_C_HEADERS
#define TACO_C_HEADERS
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <math.h>
#include <complex.h>
#define TACO_MIN(_a,_b) ((_a) < (_b) ? (_a) : (_b))
#define TACO_MAX(_a,_b) ((_a) > (_b) ? (_a) : (_b))
#ifndef TACO_TENSOR_T_DEFINED
#define TACO_TENSOR_T_DEFINED
typedef enum { taco_mode_dense, taco_mode_sparse } taco_mode_t;
typedef struct {
  int32_t      order;         // tensor order (number of modes)
  int32_t*     dimensions;    // tensor dimensions
  int32_t      csize;         // component size
  int32_t*     mode_ordering; // mode storage ordering
  taco_mode_t* mode_types;    // mode storage types
  uint8_t***   indices;       // tensor index data (per mode)
  uint8_t*     vals;          // tensor values
  int32_t      vals_size;     // values array size
} taco_tensor_t;
#endif
#endif

int assemble(taco_tensor_t *A, taco_tensor_t *B, taco_tensor_t *C) {
  int A1_dimension = (int)(A->dimensions[A->mode_ordering[0]]);
  int A2_dimension = (int)(A->dimensions[A->mode_ordering[1]]);
  double* restrict A_vals = (double*)(A->vals);
  int A_vals_size = A->vals_size;
  int B1_dimension = (int)(B->dimensions[B->mode_ordering[0]]);
  int B2_dimension = (int)(B->dimensions[B->mode_ordering[1]]);
  int* restrict C2_pos = (int*)(C->indices[1][0]);
  int* restrict C2_coord = (int*)(C->indices[1][1]);

  for (int32_t iB = 0; iB < B1_dimension; iB++) {
    for (int32_t kB = 0; kB < B2_dimension; kB++) {
      int32_t pB2 = iB * B2_dimension + kB;
      for (int32_t pC2 = C2_pos[kB]; pC2 < C2_pos[(kB + 1)]; pC2++) {
        int32_t jC = C2_coord[pC2];
        int32_t pA2 = iB * A2_dimension + jC;
      }
    }
  }

  A_vals = (double*)malloc(sizeof(double) * A1_dimension * A2_dimension);
  A_vals_size = A1_dimension * A2_dimension;

  A->vals = (uint8_t*)A_vals;
  A->vals_size = A_vals_size;
  return 0;
}

int compute(taco_tensor_t *A, taco_tensor_t *B, taco_tensor_t *C) {
  int A1_dimension = (int)(A->dimensions[A->mode_ordering[0]]);
  int A2_dimension = (int)(A->dimensions[A->mode_ordering[1]]);
  double* restrict A_vals = (double*)(A->vals);
  int B1_dimension = (int)(B->dimensions[B->mode_ordering[0]]);
  int B2_dimension = (int)(B->dimensions[B->mode_ordering[1]]);
  double* restrict B_vals = (double*)(B->vals);
  int* restrict C2_pos = (int*)(C->indices[1][0]);
  int* restrict C2_coord = (int*)(C->indices[1][1]);
  double* restrict C_vals = (double*)(C->vals);

  #pragma omp parallel for
  for (int32_t pA = 0; pA < A1_dimension * A2_dimension; pA++) {
    A_vals[pA] = 0.0;
  }
  #pragma omp parallel for
  for (int32_t iB = 0; iB < B1_dimension; iB++) {
    for (int32_t kB = 0; kB < B2_dimension; kB++) {
      int32_t pB2 = iB * B2_dimension + kB;
      double tk = B_vals[pB2];
      for (int32_t pC2 = C2_pos[kB]; pC2 < C2_pos[(kB + 1)]; pC2++) {
        int32_t jC = C2_coord[pC2];
        int32_t pA2 = iB * A2_dimension + jC;
        A_vals[pA2] = A_vals[pA2] + tk * C_vals[pC2];
      }
    }
  }
  return 0;
}

/************************ GENERATED CODE ENDS HERE ************************/

taco_tensor_t* init_taco_tensor_t(int32_t order, int32_t csize,
                                  int32_t* dimensions, int32_t* modeOrdering,
                                  taco_mode_t* modeTypes) {
  taco_tensor_t *t = (taco_tensor_t*) malloc(sizeof(taco_tensor_t));
  t->order = order;
  t->dimensions = dimensions;
  t->mode_ordering = modeOrdering;
  t->mode_types = modeTypes;
  t->csize = csize;

  t->indices = (uint8_t***) malloc(order * sizeof(uint8_t***));
  for (int32_t i = 0; i < order; i++) {
    switch (t->mode_types[i]) {
      case taco_mode_dense:
        t->indices[i] = (uint8_t**) malloc(1 * sizeof(uint8_t**));
        break;
      case taco_mode_sparse:
        t->indices[i] = (uint8_t**) malloc(2 * sizeof(uint8_t**));
        break;
    }
  }

  return t;
}

void deinit_taco_tensor_t(taco_tensor_t* t) {
  for (int i = 0; i < t->order; i++) {
    free(t->indices[i]);
  }
  free(t->indices);
  free(t);
}

int main() {
  //     |1 2 3|
  // B = |4 5 6|, stored as a dense matrix:
  //     |7 8 9|
  double B_vals[9] = {1, 2, 3, 4, 5, 6, 7, 8, 9};

  //     |6 0 9 8|
  // C = |0 0 0 0|, stored as a compressed sparse row (CSR) matrix:
  //     |5 0 0 7|
  int32_t C_pos[4] = {0, 3, 3, 5};
  int32_t C_idx[5] = {0, 2, 3, 0, 3};
  double C_vals[5] = {6, 9, 8, 5, 7};

  // Wrap B in an instance of taco_tensor_t:
  int32_t B_dims[2] = {3, 3};  // B is a 3 x 3 matrix
  int32_t B_mode_ordering[2] = {0, 1};  // B is stored in row-major order
  taco_mode_t B_mode_types[2] = {taco_mode_dense, taco_mode_dense};  // Dense matrices correspond to the (dense, dense) format
  taco_tensor_t *B = init_taco_tensor_t(2 /* B is an order-2 tensor (matrix) */, sizeof(double), B_dims, B_mode_ordering, B_mode_types);
  B->vals = (uint8_t*)B_vals;

  // Wrap C in another instance of taco_tensor_t:
  int32_t C_dims[2] = {3, 4};  // C is a 3 x 4 matrix
  int32_t C_mode_ordering[2] = {0, 1};  // C is stored in row-major order
  taco_mode_t C_mode_types[2] = {taco_mode_dense, taco_mode_sparse};  // CSR matrices correspond to the (dense, sparse) format
  taco_tensor_t *C = init_taco_tensor_t(2 /* C is an order-2 tensor (matrix) */, sizeof(double), C_dims, C_mode_ordering, C_mode_types);
  C->indices[1][0] = (uint8_t*)C_pos;  // The first array of a sparse mode/dimension corresponds to the pos array in the CSR format
  C->indices[1][1] = (uint8_t*)C_idx;  // The second array of a sparse mode/dimension corresponds to the idx array in the CSR format
  C->vals = (uint8_t*)C_vals;

  // Initialize an instance of taco_tensor_t for the result A:
  int32_t A_dims[2] = {3, 4};  // The result of A = B * C is a 3 x 4 matrix
  int32_t A_mode_ordering[2] = {0, 1};  // A will be stored in row-major order
  taco_mode_t A_mode_types[2] = {taco_mode_dense, taco_mode_dense};  // A will be stored as a dense matrix
  taco_tensor_t *A = init_taco_tensor_t(2 /* A is an order-2 tensor (matrix) */, sizeof(double), A_dims, A_mode_ordering, A_mode_types);

  assemble(A, B, C);  // Initialize A's data structures
  compute(A, B, C);   // Compute the values of A = B * C

  // Print out the result of A = B * C
  double *A_vals = (double*)A->vals;
  printf("A = \n");
  for (int i = 0; i < 3; ++i) {
    printf("    ");
    for (int j = 0; j < 4; ++j) {
      printf("%f ", A_vals[i * 4 + j]);
    }
    printf("\n");
  }

  // Clean-up
  deinit_taco_tensor_t(A);
  deinit_taco_tensor_t(B);
  deinit_taco_tensor_t(C);

  return 0;
}
```
