### ISSUE TITLE
Cannot execute with CUDA

### ISSUE THREAD

**Issue by richard-wwu** [tensor-compiler/taco#238]
I am having trouble executing a dense matrix multiplication with TACO and CUDA. I built Taco with the -DCUDA=ON switch and tried to execute dense matrix multiplication as follows:
`./bin/taco "a(i,j) = b(i,k) * c(k,j)" -time=200 -g=b:r -g=c:r -cuda`
This fails with the error message
```
/tmp/taco_tmp_3C1LT0/dkxqdjvzczw6.cu(198): error: identifier "yield" is undefined

1 error detected in the compilation of "/tmp/tmpxft_0000b7b3_00000000-8_dkxqdjvzczw6.cpp1.ii".
Error at /home/r/r_schu41/taco/src/codegen/module.cpp:146 in compile:
 Compilation command failed:
nvcc -w -O3 -Xcompiler "-fPIC -shared -ffast-math -O3" --generate-code arch=compute_70,code=sm_70 /tmp/taco_tmp_3C1LT0/dkxqdjvzczw6.cu /tmp/taco_tmp_3C1LT0/dkxqdjvzczw6_shims.cpp -o /tmp/taco_tmp_3C1LT0/dkxqdjvzczw6.so
returned 256
Aborted
```
I also get the same error when trying the `./bin/taco-tensor_times_vector` example.
Can you help me sort out this issue?
Many thanks in advance!

**Comment by stephenchouca** [comment]
It looks like taco is trying to use the GPU backend to compile code that gets generated for implementing iterators over `Tensor` objects. That code should probably just be compiled for CPU though even if the GPU backend is enabled. @RSenApps is this something you can take a look at?
