### ISSUE TITLE
Kernels no longer emit mode_ordering

### ISSUE THREAD

**Issue by drhagen** [tensor-compiler/taco#255]
[Commit a05472](https://github.com/tensor-compiler/taco/commit/a05472f2d91b5154808afaab2f5893e103701b79) eliminated the use of `mode_ordering` in all kernels. Is the mode ordering feature slated for removable?

`taco 'y(i) = A(i,j) * x(j)'`

Before this commit:
```
int compute(taco_tensor_t *y, taco_tensor_t *A, taco_tensor_t *x) {
  double* restrict y_vals = (double*)(y->vals);
  int A1_dimension = (int)(A->dimensions[A->mode_ordering[0]]);
  int A2_dimension = (int)(A->dimensions[A->mode_ordering[1]]);
  double* restrict A_vals = (double*)(A->vals);
  double* restrict x_vals = (double*)(x->vals);

  #pragma omp parallel for
  for (int32_t iA = 0; iA < A1_dimension; iA++) {
    double tj = 0.0;
    for (int32_t jA = 0; jA < A2_dimension; jA++) {
      int32_t pA2 = iA * A2_dimension + jA;
      tj += A_vals[pA2] * x_vals[jA];
    }
    y_vals[iA] = tj;
  }
  return 0;
}
```

Now:
```
int compute(taco_tensor_t *y, taco_tensor_t *A, taco_tensor_t *x) {
  double* restrict y_vals = (double*)(y->vals);
  int A1_dimension = (int)(A->dimensions[0]);
  int A2_dimension = (int)(A->dimensions[1]);
  double* restrict A_vals = (double*)(A->vals);
  double* restrict x_vals = (double*)(x->vals);

  #pragma omp parallel for schedule(static)
  for (int32_t iA = 0; iA < A1_dimension; iA++) {
    double tj = 0.0;
    for (int32_t jA = 0; jA < A2_dimension; jA++) {
      int32_t pA2 = iA * A2_dimension + jA;
      tj += A_vals[pA2] * x_vals[jA];
    }
    y_vals[iA] = tj;
  }
  return 0;
}
```

**Comment by stephenchouca** [comment]
We intend to retain the `mode_ordering` array in `taco_tensor_t` for user convenience. The generated code can hardcode this mapping though and thus does not need to use the `mode_ordering` array.

**Comment by drhagen** [comment]
Say I want a kernel for the matrix-vector product of a CSC matrix (`mode_types = [dense, sparse]` and `mode_ordering = [1, 0]`). Previously, I did `taco 'y(i) = A(i,j) * x(j)' -f=A:ds` and it would make a kernel that works for CSR and CSC matrices, but now it only works for CSR matrices. How do I generate the kernel for CSC matrices?

**Comment by stephenchouca** [comment]
`taco "y(i) = A(i,j) * x(j)" -f=A:ds` should in fact only generate code that works for CSR matrices. To generate code for CSC matrices, you need to explicitly specify the mode ordering for `A` in the format descriptor (i.e., `-f=A:ds:1,0`).

**Comment by drhagen** [comment]
> To generate code for CSC matrices, you need to explicitly specify the mode ordering for `A` in the format descriptor (i.e., `-f=A:ds:1,0`).

Ok, that's new and exactly what I was looking for. I think this is a good change to the design. The help string for the taco command line tool just does not mention this yet.

**Comment by stephenchouca** [comment]
taco tool has actually supported that for quite some time; I think we've just forgotten to document it all this time. I will update the help string to document that feature. Thanks for pointing it out.
