### ISSUE TITLE
Failing unit test (seg fault

### ISSUE THREAD

**Issue by pauldrewstri** [tensor-compiler/taco#257]
Running the units tests, some pass, but I get a segfault.  Any ideas on how to debug further?

test_dtype_conversion (__main__.TestDataTypeMethods) ... ok
test_dtype_equality (__main__.TestDataTypeMethods) ... ok
test_dtype_inspectors (__main__.TestDataTypeMethods) ... ok
test_format_methods (__main__.TestFormatMethods) ... ok
test_mode_format_methods (__main__.TestFormatMethods) ... ok
test_iterator (__main__.TestIO) ... ok
test_to_and_from_np_and_sp (__main__.TestIO) ... FAIL
test_write_then_read_compressed (__main__.TestIO) ... Segmentation fault (core dumped)

I'm running python 3.7.2

**Comment by stephenchouca** [comment]
Does the C++ test suite run successfully?

**Comment by pauldrewstri** [comment]
Yes, the C++ test suite runs fine:

[----------] Global test environment tear-down
[==========] 770 tests from 267 test cases ran. (668824 ms total)
[  PASSED  ] 770 tests.

  YOU HAVE 8 DISABLED TESTS

Rather verbose, but here is my CMAKE config if its helpful:

-- Cache values
CMAKE_AR:FILEPATH=/usr/bin/ar
CMAKE_BUILD_TYPE:STRING=Release
CMAKE_COLOR_MAKEFILE:BOOL=ON
CMAKE_CXX_COMPILER:FILEPATH=/usr/bin/c++
CMAKE_CXX_FLAGS:STRING=
CMAKE_CXX_FLAGS_DEBUG:STRING=-g
CMAKE_CXX_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG
CMAKE_CXX_FLAGS_RELEASE:STRING=-O3 -DNDEBUG
CMAKE_CXX_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG
CMAKE_C_COMPILER:FILEPATH=/usr/bin/cc
CMAKE_C_FLAGS:STRING=
CMAKE_C_FLAGS_DEBUG:STRING=-g
CMAKE_C_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG
CMAKE_C_FLAGS_RELEASE:STRING=-O3 -DNDEBUG
CMAKE_C_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG
CMAKE_EXE_LINKER_FLAGS:STRING=
CMAKE_EXE_LINKER_FLAGS_DEBUG:STRING=
CMAKE_EXE_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_EXE_LINKER_FLAGS_RELEASE:STRING=
CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_EXPORT_COMPILE_COMMANDS:BOOL=OFF
CMAKE_INSTALL_BINDIR:PATH=bin
CMAKE_INSTALL_DATADIR:PATH=
CMAKE_INSTALL_DATAROOTDIR:PATH=share
CMAKE_INSTALL_DOCDIR:PATH=
CMAKE_INSTALL_INCLUDEDIR:PATH=include
CMAKE_INSTALL_INFODIR:PATH=
CMAKE_INSTALL_LIBDIR:PATH=lib
CMAKE_INSTALL_LIBEXECDIR:PATH=libexec
CMAKE_INSTALL_LOCALEDIR:PATH=
CMAKE_INSTALL_LOCALSTATEDIR:PATH=var
CMAKE_INSTALL_MANDIR:PATH=
CMAKE_INSTALL_OLDINCLUDEDIR:PATH=/usr/include
CMAKE_INSTALL_PREFIX:PATH=/usr/local
CMAKE_INSTALL_SBINDIR:PATH=sbin
CMAKE_INSTALL_SHAREDSTATEDIR:PATH=com
CMAKE_INSTALL_SYSCONFDIR:PATH=etc
CMAKE_LINKER:FILEPATH=/usr/bin/ld
CMAKE_MAKE_PROGRAM:FILEPATH=/usr/bin/make
CMAKE_MODULE_LINKER_FLAGS:STRING=
CMAKE_MODULE_LINKER_FLAGS_DEBUG:STRING=
CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_MODULE_LINKER_FLAGS_RELEASE:STRING=
CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_NM:FILEPATH=/usr/bin/nm
CMAKE_OBJCOPY:FILEPATH=/usr/bin/objcopy
CMAKE_OBJDUMP:FILEPATH=/usr/bin/objdump
CMAKE_RANLIB:FILEPATH=/usr/bin/ranlib
CMAKE_SHARED_LINKER_FLAGS:STRING=
CMAKE_SHARED_LINKER_FLAGS_DEBUG:STRING=
CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_SHARED_LINKER_FLAGS_RELEASE:STRING=
CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_SKIP_INSTALL_RPATH:BOOL=NO
CMAKE_SKIP_RPATH:BOOL=NO
CMAKE_STATIC_LINKER_FLAGS:STRING=
CMAKE_STATIC_LINKER_FLAGS_DEBUG:STRING=
CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_STATIC_LINKER_FLAGS_RELEASE:STRING=
CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_STRIP:FILEPATH=/usr/bin/strip
CMAKE_VERBOSE_MAKEFILE:BOOL=FALSE
CUDA:BOOL=ON
CUDA_64_BIT_DEVICE_CODE:BOOL=ON
CUDA_ATTACH_VS_BUILD_RULE_TO_CUDA_FILE:BOOL=ON
CUDA_BUILD_CUBIN:BOOL=OFF
CUDA_BUILD_EMULATION:BOOL=OFF
CUDA_CUDART_LIBRARY:FILEPATH=/usr/local/cuda/lib64/libcudart.so
CUDA_CUDA_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libcuda.so
CUDA_GENERATED_OUTPUT_DIR:PATH=
CUDA_HOST_COMPILATION_CPP:BOOL=ON
CUDA_HOST_COMPILER:FILEPATH=/usr/bin/cc
CUDA_NVCC_EXECUTABLE:FILEPATH=/usr/local/cuda/bin/nvcc
CUDA_NVCC_FLAGS:STRING=
CUDA_NVCC_FLAGS_DEBUG:STRING=
CUDA_NVCC_FLAGS_MINSIZEREL:STRING=
CUDA_NVCC_FLAGS_RELEASE:STRING=
CUDA_NVCC_FLAGS_RELWITHDEBINFO:STRING=
CUDA_PROPAGATE_HOST_FLAGS:BOOL=ON
CUDA_SDK_ROOT_DIR:PATH=CUDA_SDK_ROOT_DIR-NOTFOUND
CUDA_SEPARABLE_COMPILATION:BOOL=OFF
CUDA_TARGET_CPU_ARCH:STRING=
CUDA_TOOLKIT_INCLUDE:PATH=/usr/local/cuda/include
CUDA_TOOLKIT_ROOT_DIR:PATH=/usr/local/cuda
CUDA_TOOLKIT_TARGET_DIR:PATH=/usr/local/cuda
CUDA_USE_STATIC_CUDA_RUNTIME:BOOL=ON
CUDA_VERBOSE_BUILD:BOOL=OFF
CUDA_VERSION:STRING=9.0
CUDA_cublas_LIBRARY:FILEPATH=/usr/local/cuda/lib64/libcublas.so
CUDA_cudart_static_LIBRARY:FILEPATH=/usr/local/cuda/lib64/libcudart_static.a
CUDA_cufft_LIBRARY:FILEPATH=/usr/local/cuda/lib64/libcufft.so
CUDA_cupti_LIBRARY:FILEPATH=/usr/local/cuda/extras/CUPTI/lib64/libcupti.so
CUDA_curand_LIBRARY:FILEPATH=/usr/local/cuda/lib64/libcurand.so
CUDA_cusolver_LIBRARY:FILEPATH=/usr/local/cuda/lib64/libcusolver.so
CUDA_cusparse_LIBRARY:FILEPATH=/usr/local/cuda/lib64/libcusparse.so
CUDA_nppc_LIBRARY:FILEPATH=/usr/local/cuda/lib64/libnppc.so
CUDA_nppi_LIBRARY:FILEPATH=CUDA_nppi_LIBRARY-NOTFOUND
CUDA_npps_LIBRARY:FILEPATH=/usr/local/cuda/lib64/libnpps.so
CUDA_rt_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/librt.so
OPENMP" Build with OpenMP execution support":BOOL=ON
OPTIMIZE:STRING=-O3
PYBIND11_CPP_STANDARD:STRING=-std=c++14
PYBIND11_INSTALL:BOOL=OFF
PYBIND11_PYTHON_VERSION:STRING=
PYBIND11_TEST:BOOL=OFF
PYTHON:BOOL=ON
PYTHON_EXECUTABLE:FILEPATH=/home/pauldrews/miniconda3/envs/pt101/bin/python3.7
PYTHON_LIBRARY:FILEPATH=/home/pauldrews/miniconda3/envs/pt101/lib/libpython3.7m.so
TACO_SHARED_LIBRARY:BOOL=ON
USE_PYTHON_INCLUDE_DIR:BOOL=OFF

**Comment by stephenchouca** [comment]
Just a guess, but it might be some issue with file IO. Can you try the following and see if any of them works?

- In `python_bindings/unit_tests.py`, disable `TestIO` by adding the decorator `@ unittest.skip` above the class definition for `TestIO` (on line 60), and then rerun the test suite.
- From a directory where you have write access, run the following program:

```python
import pytaco as pt
from pytaco import dense
size = 10
x = pt.tensor([size], pt.format([dense]))
y = pt.tensor([size], pt.format([dense]))
for i in range(size):
    x.insert([i], i)
i = pt.get_index_vars(1)
y[i] = x[i]
for i in range(size):
    assert(y[i] == i)
pt.write("y.tns",y)
z = pt.read("y.tns",pt.dense)
for i in range(size):
    assert(z[i] == i)
```

- Clone commit `6c10882` (instead of the latest one) and rerun the test suite.

**Comment by pauldrewstri** [comment]
Disabling that unit test gets me further, now I have a GPUassert:

```
test_tensor_from_numpy (__main__.TestTensorCreation) ... ok
test_values_correctly_set (__main__.TestTensorCreation) ... ok
test_evaluate (__main__.testParsers) ... GPUassert: an illegal memory access was encountered /tmp/taco_tmp_SF9HjV/pbrzz1jib312.cu 41
```
Your code snippet runs fine, no asserts.

When I checkout commit `6c10882`, re-compile, and run unit tests I get:

```
test_dtype_conversion (__main__.TestDataTypeMethods) ... ok
test_dtype_equality (__main__.TestDataTypeMethods) ... ok
test_dtype_inspectors (__main__.TestDataTypeMethods) ... ok
test_format_methods (__main__.TestFormatMethods) ... ok
test_mode_format_methods (__main__.TestFormatMethods) ... ok
test_to_and_from_np_and_sp (__main__.TestIOFuncs) ... /tmp/taco_tmp_EOxvOL/v7pi36j2vyye.cu(88): error: expected an expression

/tmp/taco_tmp_EOxvOL/v7pi36j2vyye.cu(88): error: identifier "yield" is undefined

2 errors detected in the compilation of "/tmp/tmpxft_00006596_00000000-8_v7pi36j2vyye.cpp1.ii".
ERROR
test_write_then_read_compressed (__main__.TestIOFuncs) ... /tmp/taco_tmp_EOxvOL/cfry5xfdkb0m.cu(123): error: expected an expression

/tmp/taco_tmp_EOxvOL/cfry5xfdkb0m.cu(123): error: identifier "yield" is undefined

2 errors detected in the compilation of "/tmp/tmpxft_0000659f_00000000-8_cfry5xfdkb0m.cpp1.ii".
ERROR
test_write_then_read_dense (__main__.TestIOFuncs) ... /tmp/taco_tmp_EOxvOL/rern7jc6aj2w.cu(88): error: expected an expression

/tmp/taco_tmp_EOxvOL/rern7jc6aj2w.cu(88): error: identifier "yield" is undefined

2 errors detected in the compilation of "/tmp/tmpxft_000065a8_00000000-8_rern7jc6aj2w.cpp1.ii".
ERROR
test_mod (__main__.TestIndexFuncs) ... ok
test_reduce (__main__.TestIndexFuncs) ... /tmp/taco_tmp_EOxvOL/3c752w1eys46.cu(70): error: expected an expression

/tmp/taco_tmp_EOxvOL/3c752w1eys46.cu(70): error: identifier "yield" is undefined

2 errors detected in the compilation of "/tmp/tmpxft_000065df_00000000-8_3c752w1eys46.cpp1.ii".
ERROR
test_get_and_set_threads (__main__.TestSchedulingCommands) ... ok
test_parallel_sched (__main__.TestSchedulingCommands) ... ok
test_array_copy_C_and_F_style (__main__.TestTensorCreation) ... Segmentation fault (core dumped)
```

**Comment by stephenchouca** [comment]
The GPU backend is still experimental and hasn't been fully tested with the Python bindings, so that might be an issue as well. Can you try rebuilding without the GPU backend and see if the full test suite runs? If that still fails, can you try the same with `TestIO` disabled and try commit `6c10882` with the full test suite (again with the GPU backend disabled)?

**Comment by pauldrewstri** [comment]
That was it, GPU backend seems to be not fully supported yet.  The tests run fine when I don't compile with GPU support.  Thanks!!

**Comment by Infinoid** [comment]
As of now, the python test suite seems to run successfully when CUDA is enabled.  So I think this issue can be closed.

I think 3d8461d is what got the tests working.

```
$ bin/taco --version
TACO version: 0.1+git 3d8461de
Built with OpenMP support.
Built with Python support.
Built with CUDA support.

Built on: 2021-05-24
CMake build type: Debug
Built with compiler: GNU C++ version 10.2.1

$ python3 python_bindings/unit_tests.py
test_dtype_conversion (__main__.TestDataTypeMethods) ... ok
test_dtype_equality (__main__.TestDataTypeMethods) ... ok
test_dtype_inspectors (__main__.TestDataTypeMethods) ... ok
test_format_methods (__main__.TestFormatMethods) ... ok
test_mode_format_methods (__main__.TestFormatMethods) ... ok
test_iterator (__main__.TestIO) ... ok
test_to_and_from_np_and_sp (__main__.TestIO) ... ok
test_write_then_read_compressed (__main__.TestIO) ... ok
test_write_then_read_dense (__main__.TestIO) ... ok
test_mod (__main__.TestIndexFuncs) ... ok
test_neg (__main__.TestIndexFuncs) ... ok
test_reduce (__main__.TestIndexFuncs) ... ok
test_get_and_set_threads (__main__.TestSchedulingCommands) ... ok
test_parallel_sched (__main__.TestSchedulingCommands) ... ok
test_array_copy_C_and_F_style (__main__.TestTensorCreation) ... ok
test_reshaped_array (__main__.TestTensorCreation) ... ok
test_tensor_from_numpy (__main__.TestTensorCreation) ... ok
test_values_correctly_set (__main__.TestTensorCreation) ... ok
test_evaluate (__main__.testParsers) ... ok

----------------------------------------------------------------------
Ran 19 tests in 182.049s

OK
```

**Comment by stephenchouca** [comment]
@Infinoid thanks for validating it!
