### ISSUE TITLE
build errors on Cygwin

### ISSUE THREAD

**Issue by jinz2014** [tensor-compiler/taco#266]
I use cygwin on a Windows laptop, and see the following errors.

Thanks for your instructions.

[  1%] Building CXX object test/CMakeFiles/gtest.dir/gtest/gtest-all.cc.o
[  2%] Building CXX object src/CMakeFiles/taco.dir/cuda.cpp.o
[  3%] Building CXX object src/CMakeFiles/taco.dir/error.cpp.o
[  4%] Building CXX object src/CMakeFiles/taco.dir/format.cpp.o
[  5%] Building CXX object src/CMakeFiles/taco.dir/taco_tensor_t.cpp.o
[  6%] Building CXX object src/CMakeFiles/taco.dir/target.cpp.o
In file included from /home/cc/taco/test/gtest/gtest-all.cc:39:0:
/home/cc/taco/test/gtest/gtest.h: In function ‘int testing::internal::posix::F                                                                                                                          ileNo(FILE*)’:
/home/cc/taco/test/gtest/gtest.h:3346:51: error: ‘fileno’ was not declared in                                                                                                                           this scope
 inline int FileNo(FILE* file) { return fileno(file); }
                                                   ^
/home/cc/taco/test/gtest/gtest.h: In function ‘char* testing::internal::posix:                                                                                                                          :StrDup(const char*)’:
/home/cc/taco/test/gtest/gtest.h:3352:57: error: ‘strdup’ was not declared in                                                                                                                           this scope
 inline char* StrDup(const char* src) { return strdup(src); }
                                                         ^
/home/cc/taco/test/gtest/gtest.h: In function ‘FILE* testing::internal::posix:                                                                                                                          :FDOpen(int, const char*)’:
/home/cc/taco/test/gtest/gtest.h:3380:71: error: ‘fdopen’ was not declared in                                                                                                                           this scope
 inline FILE* FDOpen(int fd, const char* mode) { return fdopen(fd, mode); }
                                                                       ^
[  7%] Building CXX object src/CMakeFiles/taco.dir/tensor.cpp.o
/home/cc/taco/test/gtest/gtest-all.cc: In constructor ‘testing::internal::Capt                                                                                                                          uredStream::CapturedStream(int)’:
/home/cc/taco/test/gtest/gtest-all.cc:9066:50: error: ‘mkstemp’ was not declar                                                                                                                          ed in this scope
     const int captured_fd = mkstemp(name_template);

**Comment by stephenchouca** [comment]
Can you try replacing line 74 in `CMakeLists.txt` with the following:

```
set(CMAKE_CXX_FLAGS "${C_CXX_FLAGS} -std=gnu++11")
```

and see if that resolves the error? (Make sure to restart the build process from scratch.)

**Comment by jinz2014** [comment]
Thanks for your solution.
