### ISSUE TITLE
question related to the -time option

### ISSUE THREAD

**Issue by guilhermeleobas** [tensor-compiler/taco#267]
When using the command-line interface, the `-time` option reports the time it takes for the kernel to execute? Or it also reports the time to load the tensors (from a file for instance)?

For example:
```sh
$ ./taco "A(i,j) = B(i,k) * C(k,j)" -f=B:dd -g=B:d -f=C:dd -g=C:d -d=B:1000,1000 -d=C:1000,1000 -time
B size: (1000 x 1000), 8000008 bytes
C size: (1000 x 1000), 8000008 bytes

Compile:  74.5896 ms
Assemble: 0.104775 ms
Compute:  448.07 ms
```

The `Compute` time reported is only for the kernel function or it also considers the time to generate `B` and `C`?

**Comment by stephenchouca** [comment]
The "compute" time only includes the time needed to compute the values of the output tensor; taco does not measure the time needed to load or generate the input tensors.
