### ISSUE TITLE
taco tool segfaults when using -time=number

### ISSUE THREAD

**Issue by guilhermeleobas** [tensor-compiler/taco#268]
Hi,

I am trying to use the TACO compiler tool to do a simple matrix multiplication but it segfaults when I use `time=any_number_greater_than_one`. I've run a debug version of TACO on lldb and the segmentation fault happens [in this line](https://github.com/tensor-compiler/taco/blob/219f6b92635a98408c2f9ee8eaecf054bce8229a/include/taco/ir/ir.h#L94) in the source code. 

Below is the command that I used to run:
```
./taco "A(i,j) = B(i,k) * C(k,j)" -f=B:dd -f=C:dd -d=B:1000,1000 -d=C:1000,1000 -i=B:b_in.tns -i=C:tns/c_in.tns -time=5
```

**Comment by stephenchouca** [comment]
Does the segfault happen before or after the benchmarking is done (i.e., are you still able to get timing numbers for assembly and compute, or does the command-line tool crash before that happens)?

**Comment by guilhermeleobas** [comment]
I can get the time for compile and assembly. So, the crash happens during benchmarking.

I can share the input files I am using if you want.

**Comment by stephenchouca** [comment]
Sure, that might be helpful.

It might also be worth trying commenting out the line where the segfault happens (i.e., the `delete node`) and see if taco still crashes then.

**Comment by guilhermeleobas** [comment]
Thanks! This solved the problem.
