### ISSUE TITLE
generating GPU kernels

### ISSUE THREAD

**Issue by dongxiao92** [tensor-compiler/taco#272]
I'm trying to use taco to generate cuda kernels of computing the sparse-matrix-dense-matrix multiplication. But I find it seems the generated 'compute' method does not runs on GPU. I show my code below.
```
                ......
                //define the format for input data
                Format input_fmt({Sparse, Sparse, Dense});
                //define the weight format
                Format weight_fmt({Dense, Dense});
                //define the format for output
                Format output_fmt({Sparse, Sparse, Dense});
                //Create tensors
                Tensor<float> input({input_h, input_w, input_c}, input_fmt);
                Tensor<float> weight({output_k, input_c}, weight_fmt);
                Tensor<float> output({input_h, input_w, output_k}, output_fmt);
                 // fill in data
                insert_sparse(input, input_data.get(), input_h, input_w, input_c);
                insert_dense(weight, weight_data.get(), output_k, input_c);

                //packing
                input.pack();
                weight.pack();
                //Form the computation expression
                IndexVar oh, ow, ok, ic; 
                output(oh, ow, ok) = input(oh, ow, ic)*weight(ok, ic);
                //Compile and assemble
                output.compile();
                output.assemble();
                //Compute
                output.compute();
```

I build taco using` cmake -DCMAKE_BUILD_TYPE=Release -DCUDA=ON .. ` and all tests in `taco-test` have passed. I use  `set_CUDA_codegen_enabled(true)` to enable cuda code generation. The generated 'compute' method is shown below.
```
int compute(taco_tensor_t *A2, taco_tensor_t *A0, taco_tensor_t *A1) {
  int A23_dimension = (int)(A2->dimensions[2]);
  float* __restrict__ A2_vals = (float*)(A2->vals);
  int A03_dimension = (int)(A0->dimensions[2]);
  int* __restrict__ A01_pos = (int*)(A0->indices[0][0]);
  int* __restrict__ A02_pos = (int*)(A0->indices[1][0]);
  float* __restrict__ A0_vals = (float*)(A0->vals);
  int A11_dimension = (int)(A1->dimensions[0]);
  int A12_dimension = (int)(A1->dimensions[1]);
  float* __restrict__ A1_vals = (float*)(A1->vals);

  int32_t pA22 = 0;
  for (int32_t pA01 = A01_pos[0]; pA01 < A01_pos[1]; pA01++) {
    for (int32_t pA02 = A02_pos[pA01]; pA02 < A02_pos[(pA01 + 1)]; pA02++) {
      for (int32_t i45A1 = 0; i45A1 < A11_dimension; i45A1++) {
        int32_t pA23 = pA22 * A23_dimension + i45A1;
        float ti46 = 0.0;
        for (int32_t i46A0 = 0; i46A0 < A03_dimension; i46A0++) {
          int32_t pA03 = pA02 * A03_dimension + i46A0;
          int32_t pA12 = i45A1 * A12_dimension + i46A0;
          ti46 = ti46 + A0_vals[pA03] * A1_vals[pA12];
        }   
        A2_vals[pA23] = ti46;
      }   
      pA22 = pA22 + 1;
    }   
  }
  return 0;
}
```
I can find the generated 'pack' methods do some memory allocation and data movement work using the unified memory model of CUDA, and gpu utilization can be observed by 'nvidia-smi'. So I'm confused if the computation really runs on GPU.

**Comment by dongxiao92** [comment]
> This computation is not running on the GPU because taco can not trivially parallelize the outer loop, which is the current prerequisite for running a computation on the GPU. The reason it can not be parallelized is because of the dependency on pA22 between loop iterations (ie not all levels of the result tensor support random insert).
> 
> If you make output {Dense, Dense, Dense} then taco should generate correct GPU code. You could then compress this output into a {Sparse, Sparse, Dense} on the CPU.
> 
> `bin/taco "output(oh, ow, ok) = input(oh, ow, ic)*weight(ok, ic)" -cuda -print-compute -f=input:ssd -f=weight:dd -f=output:ssd`
> does not generate parallel code, but
> `bin/taco "output(oh, ow, ok) = input(oh, ow, ic)*weight(ok, ic)" -cuda -print-compute -f=input:ssd -f=weight:dd -f=output:ddd`
> does.
> 
> This issue #127 is really out of date, but I am currently implementing the new scheduling language, which will allow for parallelizing these type of loops. In this case each parallel element will first determine its starting pA22 before proceeding with the normal computation. It will also allow specifying much more useful GPU schedules (the current schedule is just 1 gpu thread per outer loop iteration, which probably will not be very good for your use case).
> 
> Please let me know if you have any other questions, but hope that helps!

Thanks for your help. I can get gpu kernels now, while the performance of generated gpu kernels cannot match the cpu conterparts. A 3-9x slow-down can be observed on my test with 15 cases.

**Comment by RSenApps** [comment]
Ok great yes that is expected due to the poor schedule. I was wondering if you had an idea in mind of how you would want this kernel to be parallelized on the gpu (how is work spread across threads, warps, and thread-blocks)? I want to verify that such a schedule can be specified with the current scheduling language design.

**Comment by dongxiao92** [comment]
@RSenApps  I actually do not have a clear answer for the best parallelization strategy on GPU. I just tried to understand the current generated kernel. For now, I think taco tries parallel the outer-most loop(i.e., oh in this example) and dispatches the computation for a single oh in the output to a CUDA thread. The data of the sparse-sparse-dense input is organized into a dense matrix with the shape of (nnz, ic) with nnz being the total non-zero points in the space of oh*ow.
Do I understand taco's parallelization right?

**Comment by RSenApps** [comment]
With the scheduling language the user will be able to specify how they would like the computation to be parallelized so it is up to you! But yes, right now it is just parallelizing the outer loop. I am going to close this issue, but feel free to watch #127 for updates over the next couple of months.
