### ISSUE TITLE
Introduce the concept of a fill-value

### ISSUE THREAD

**Issue by hameerabbasi** [tensor-compiler/taco#283]
Is there a concept related to fill-values in TACO? With arbitrary reductions and element-wise ops (#276), and fill-value, the functionality of this library is more-or-less a strict superset of PyData/Sparse, and I was considering using this library for that purpose.

To elaborate, fill-values are values that you don't store. For regular sparse arrays, this is 0.

**Comment by rohany** [comment]
Closing as we are in the process of merging the array_algebra branch, which enables arbitrary fill values in TACO.
