### ISSUE TITLE
nvcc fatal   : Unknown option 'fopenmp'

### ISSUE THREAD

**Issue by zjjzby** [tensor-compiler/taco#301]
When I try to use the openmp and cuda simultaneously to  compile the spmv example, I meet with this errors. The error information is as follows

nvcc fatal   : Unknown option 'fopenmp'
Error at /taco/taco-gpu/taco/src/codegen/module.cpp:154 in compile:
 Compilation command failed:
nvcc -w -O3 -Xcompiler "-fPIC -shared -ffast-math -O3" --generate-code arch=compute_61,code=sm_61 -fopenmp /tmp/taco_tmp_9f30I1/32v4jeazaskf.cu /tmp/taco_tmp_9f30I1/32v4jeazaskf_shims.cpp -o /tmp/taco_tmp_9f30I1/32v4jeazaskf.so -lm
returned 256

**Comment by stephenchouca** [comment]
Should be fixed with fbda4cb.
