### ISSUE TITLE
nvcc error: "C_val" has already been declared in the current scope

### ISSUE THREAD

**Issue by Infinoid** [tensor-compiler/taco#311]
The [scheduling.parallelizeAtomicReduction](https://github.com/tensor-compiler/taco/blob/master/test/tests-scheduling.cpp#L320) test fails for cuda builds.

Compilation dies with:
```
/tmp/taco_tmp_eGqfbC/1wry7ti8f7ci.cu(153): error: "C_val" has already been declared in the current scope
```

Taco generates this code:

```
void computeDeviceKernel0(taco_tensor_t * __restrict__ A, taco_tensor_t * __restrict__ B, double &C_val){
  int* __restrict__ A1_pos = (int*)(A->indices[0][0]);
  int* __restrict__ A1_crd = (int*)(A->indices[0][1]);
  double* __restrict__ A_vals = (double*)(A->vals);
  int B1_dimension = (int)(B->dimensions[0]);
  double* __restrict__ B_vals = (double*)(B->vals);

  int32_t block = blockIdx.x;
  int32_t thread = (threadIdx.x % (2));
  if (threadIdx.x >= 2) {
    return;
  }

  double C_val = 0.0;
```

The `C_val` local variable is redundant with the function parameter of the same name.

This failure started occurring when PR #304 was merged.

If it helps, I added before/after debug statements around [the new call to scalarPromote](https://github.com/tensor-compiler/taco/blob/master/src/tensor.cpp#L557) and I see:

```
before: suchthat(forall(block, forall(thread, where(C += ti1, forall(i1, ti1 += A(i) * B(i))), GPUThread, Atomics), GPUBlock, Atomics), split(i, i0, i1, 2) and split(i0, block, thread, 2))
after: suchthat(forall(block, where(C += C, forall(thread, where(C += ti1, forall(i1, ti1 += A(i) * B(i))), GPUThread, Atomics)), GPUBlock, Atomics), split(i, i0, i1, 2) and split(i0, block, thread, 2))
```

In this test, the `C` tensor is 0-dimensional (scalar), and the emitted code simplifies it to a double pointer.  Should this parameter have a `_val` suffix?

**Comment by stephenchouca** [comment]
I've pushed some changes to master that should fix this bug. Let me know if you still see the error. Thanks!

**Comment by Infinoid** [comment]
Works for me, thanks!
