### ISSUE TITLE
taco CLI fails with "compile method must be called before assemble"

### ISSUE THREAD

**Issue by kovach** [tensor-compiler/taco#366]
I tried a basic example similar to one from "taco: A Tool to Generate Tensor Algebra Kernels":

```
> taco "A(i,j) = M(i,j)" -i=M:foo.mtx -f=M:dd -time
```
after successfully reading the mtx file the command fails with:
```
Compile:  88.0345 ms
terminate called after throwing an instance of 'taco::TacoException'
  what():  Error at /home/scott/Dropbox/taco/src/tensor.cpp:713 in assemble:
 The compile method must be called before assemble.
```

edit: also, binding to the wrong name (e.g. `-i=N:foo.mtx`) causes a seg faullt

**Comment by Infinoid** [comment]
You're right.  I submitted a patch to fix the `compile method must be called before assemble` error.
