### ISSUE TITLE
What's the difference between Tiramisu and TACO compiler

### ISSUE THREAD

**Issue by jinderek** [tensor-compiler/taco#383]
I searched through the internet but can not find the comparison.
AFAIK, they are both tensor compiler.

**Comment by rohany** [comment]
A core difference (from scanning the tiramisu paper) is that Tiramisu targets mainly dense computations, while TACO focuses on operations over sparse tensors stored in a variety of compressed formats.

**Comment by weiya711** [comment]
@jinderek It seems that @rohany answered your question so I'm closing this issue now. If you have any followup questions about TACO please submit a new git issue.
