### ISSUE TITLE
scheduling_eval.spmvGPU test failure

### ISSUE THREAD

**Issue by Infinoid** [tensor-compiler/taco#389]
PR #362 introduced a cuda test failure.

Configure with `-DCUDA=ON`.  Then run the scheduling_eval.spmvGPU test:

`bin/taco-test --gtest_filter=scheduling_eval.spmvGPU`

With revision 468ad7f (merge #362):

```
% bin/taco-test --gtest_filter=scheduling_eval.spmvGPU
Note: Google Test filter = scheduling_eval.spmvGPU
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from scheduling_eval
[ RUN      ] scheduling_eval.spmvGPU
zsh: segmentation fault (core dumped)  bin/taco-test --gtest_filter=scheduling_eval.spmvGPU
```

With revision `468ad7f^` (master branch prior to merge):

```
% bin/taco-test --gtest_filter=scheduling_eval.spmvGPU
Note: Google Test filter = scheduling_eval.spmvGPU
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from scheduling_eval
[ RUN      ] scheduling_eval.spmvGPU
[       OK ] scheduling_eval.spmvGPU (8408 ms)
[----------] 1 test from scheduling_eval (8408 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (8408 ms total)
[  PASSED  ] 1 test.
```

When I trigger it in gdb:
```gdb
Thread 1 "taco-test" received signal SIGSEGV, Segmentation fault.
taco::LowererImpl::declLocatePosVars (this=0x55555665ddf0, locators=...)
    at /home/infinoid/workspace/taco/git/src/lower/lowerer_impl.cpp:2288
2288	        taco_iassert(isValue(locate.getResults()[1], true));
(gdb) p locateIterator.hasLocate()
$1 = false
(gdb) p locate
$2 = {content = std::shared_ptr<taco::ModeFunction::Content> (empty) = {get() = 0x0}}
```

Apparently the ModeFormat claims that it can't locate, and `locateIterator.locate()` returns a NULL pointer.  The call to locate.getResults() then segfaults.

I also noticed that the coords argument to `locateIterator.locate()` is a vector of 2 values in this case, it contains `fposA` twice.  Normally coords only contains a single Var.

```gdb
(gdb) p coords
$1 = std::vector of length 2, capacity 2 = {{<taco::ir::IRHandle> = {<taco::util::IntrusivePtr<taco::ir::IRNode const>> = {
        _vptr.IntrusivePtr = 0x555555a0e778 <vtable for taco::ir::Expr+16>, 
        ptr = 0x55555665c8e0}, <No data fields>}, <No data fields>}, 
  {<taco::ir::IRHandle> = {<taco::util::IntrusivePtr<taco::ir::IRNode const>> = {
        _vptr.IntrusivePtr = 0x555555a0e778 <vtable for taco::ir::Expr+16>, 
        ptr = 0x55555665c8e0}, <No data fields>}, <No data fields>}}
```

**Comment by stephenchouca** [comment]
Can be reproduced with following (non GPU-specific) schedule: `taco "y(i) = A(i,j) * x(j)" -f=A:dd -s="fuse(i,j,f),pos(f,fpos,A),split(fpos, block, fpos1,2048),split(fpos1, warp, fpos2,256),split(fpos2, thread, thread_nz,8),reorder(block, warp, thread, thread_nz),precompute(A(i,j)*x(j), thread_nz, thread_nz_pre),unroll(thread_nz_pre,8)"` (the bug is triggered by the `unroll` command)

**Comment by Infinoid** [comment]
Stephen's reproducer simplifies to:

`taco "y(i) = A(i,j) * x(j)" -f=A:ds -s="fuse(i,j,f),pos(f,fpos,A),precompute(A(i,j)*x(j),fpos,fpre),unroll(fpre,2)"`

**Comment by stephenchouca** [comment]
I believe the latest commit on master should fix this bug. @Infinoid can you verify that is the case?

**Comment by Infinoid** [comment]
Yep, looks good.  Your commit fixes `scheduling_eval.spmvGPU`, and also fixes `where_spmm/lower_compile/0` on CUDA builds.

Thanks!
