### ISSUE TITLE
Old version of Pybind11 find the wrong python version

### ISSUE THREAD

**Issue by jamesETsmith** [tensor-compiler/taco#397]
## Problem
Hello! I just wanted to give you all a heads up that you might want to update the `pybind11` that's packaged with `taco`.  The version of `pybind11` you've included has some problems when they search for python and can sometimes target the wrong python version (which happened to me when I tried to make the python bindings for `taco`). You can check out this `pybind11` issue (pybind/pybind11/issues/1090) and PR (pybind/pybind11/pull/2370) for more details.

## Version Info
- Taco: 1114197
- CC/CXX: gcc 10.2
- Python 3.9.1

## Solution
Updating to the latest version of `pybind11` fixed this for me.

Happy to make a PR for this if that'd be helpful.

**Comment by RawnH** [comment]
PyBind should actually be a git sub-module. PR #400 will address this and will be removed from draft once I figure out why one of the unit tests fail.
