### ISSUE TITLE
windowing/assignment.windowing/1 test fails with OpenMP

### ISSUE THREAD

**Issue by stkaplan** [tensor-compiler/taco#409]
Looks like a test added in PR #372 fails when built with OpenMP. Runs fine without OpenMP.

```
176/182 Testing: */assignment.windowing/*
176/182 Test: */assignment.windowing/*
Command: "/home/sam/work/taco/taco/build/bin/taco-test" "--gtest_filter=*/assignment.windowing/*"
Directory: /home/sam/work/taco/taco/build/test
"*/assignment.windowing/*" start time: Feb 16 15:24 EST
Output:
----------------------------------------------------------
Note: Google Test filter = */assignment.windowing/*
[==========] Running 2 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 2 tests from windowing/assignment
[ RUN      ] windowing/assignment.windowing/0
[       OK ] windowing/assignment.windowing/0 (2241 ms)
[ RUN      ] windowing/assignment.windowing/1
/tmp/taco_tmp_q4g2Kh/mvgwt6s86yqy.c: In function ‘compute’:
/tmp/taco_tmp_q4g2Kh/mvgwt6s86yqy.c:136:7: error: break statement used with OpenMP for loop
  136 |       break;
      |       ^~~~~
Error at /home/sam/work/taco/taco/src/codegen/module.cpp:145 in compile:
 Compilation command failed:
cc -O3 -ffast-math -std=c99 -shared -fPIC -fopenmp /tmp/taco_tmp_q4g2Kh/mvgwt6s86yqy.c  -o /tmp/taco_tmp_q4g2Kh/mvgwt6s86yqy.so -lm
returned 256
[  FAILED  ] windowing/assignment.windowing/1, where GetParam() = compressed (597 ms)
[----------] 2 tests from windowing/assignment (2838 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test case ran. (2838 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] windowing/assignment.windowing/1, where GetParam() = compressed

 1 FAILED TEST
<end of output>
Test time =   3.76 sec
```

**Comment by rohany** [comment]
For sake of reproduction, how did you compile the tests/taco to use openmp?

**Comment by stephenchouca** [comment]
I was able to reproduce the issue by running cmake with `-DOPENMP=ON`.

**Comment by rohany** [comment]
Does `-DOPENMP=ON` work on mac? I see a series of errors trying to build it:
```

**Comment by stephenchouca** [comment]
> Does `-DOPENMP=ON` work on mac? I see a series of errors trying to build it:
> 
> ```
> [  1%] Building CXX object test/CMakeFiles/taco-gtest.dir/gtest/gtest-all.cc.o
> [  1%] Building CXX object src/CMakeFiles/taco.dir/cuda.cpp.o
> [  3%] Building CXX object src/CMakeFiles/taco.dir/ir_tags.cpp.o
> [  4%] Building CXX object src/CMakeFiles/taco.dir/error.cpp.o
> clang: error: unsupported option '-fopenmp'
> [  4%] Building CXX object src/CMakeFiles/taco.dir/format.cpp.o
> [  5%] Building CXX object src/CMakeFiles/taco.dir/taco_tensor_t.cpp.o
> make[3]: *** [test/CMakeFiles/taco-gtest.dir/gtest/gtest-all.cc.o] Error 1
> make[2]: *** [test/CMakeFiles/taco-gtest.dir/all] Error 2
> make[2]: *** Waiting for unfinished jobs....
> [  6%] Building CXX object src/CMakeFiles/taco.dir/target.cpp.o
> [  7%] Building CXX object src/CMakeFiles/taco.dir/tensor.cpp.o
> clang: error: unsupported option '-fopenmp'
> [  8%] Building CXX object src/CMakeFiles/taco.dir/type.cpp.o
> clang: error: unsupported option '-fopenmp'
> clang: error: unsupported option '-fopenmp'
> clang: error: unsupported option '-fopenmp'
> clang: error: unsupported option '-fopenmp'
> clang: error: unsupported option '-fopenmp'
> clang: error: unsupported option '-fopenmp'
> ```

Not out of the box, since Apple Clang does not support OpenMP. I believe it's possible to install OpenMP on MacOS, though I have not tried it myself. If you have access to a Linux machine, that might be the easiest way to run TACO with OpenMP.
