### ISSUE TITLE
Result ptr variable not initialized properly

### ISSUE THREAD

**Issue by Lugatod** [tensor-compiler/taco#42]
Using a debug option for the generated code leads to a crash in the test suite.
`export TACO_CFLAGS="-g"` or "-O0"

**Comment by stephenchouca** [comment]
@Lugatod 635bb4d should fix this. Can you verify that this is indeed the case? I was unable to reproduce the original crash on my machine.

**Comment by Lugatod** [comment]
Yes the bug is fixed
