### ISSUE TITLE
precompute generates invalid code when I give it differing index variable names

### ISSUE THREAD

**Issue by Infinoid** [tensor-compiler/taco#431]
This works: `taco 'A(i) = B(i)*1' -s='precompute(B(i)*1,i,i)'`
This breaks: `taco 'A(i) = B(i)*1' -s='precompute(B(i)*1,i,j)'`

These two commands generate quite different output.  The output of the first one appears correct at first glance; the output of the second one has several issues: 

* somehow, the size of the workspace stopped being equal to the input size, and is now hardcoded to 42
* the main copy loop now loops over the workspace var, not the input var, and is more complicated as a result
* the output loop now refers to two index variables that are never defined (`iA` and `iworkspace`)

If you then add `-f=B:s` so that the B tensor is sparse, the output of the first case still appears correct, but the second one now has an additional problem:
* the main copy loop now writes to workspace position`j`.  `j` is initialized to `i`, but never updated from one loop iteration to the next

[The full outputs are here](https://gist.github.com/Infinoid/bb2dd157b2d750ebe6cbaca4b99e8db9).  This was using a Debug build of taco with no features (openmp, cuda, or python).

There's some overlap between this and comments in issue #347.  But I think the `isLowerable` failure is a separate issue.

**Comment by rohany** [comment]
I don't know much about this, but it looks like the two commands you have written are the same.

**Comment by Infinoid** [comment]
The difference is in the `precompute()` scheduling directive, the `,i` or `,j` at the end.

Giving it the same IndexVar name twice works.  Giving two different names breaks.

**Comment by rohany** [comment]
Ah my bad, I stared at this for a while and couldn't tell that the `i` and `j` were different.

**Comment by weiya711** [comment]
This is a known bug and happens whenever `i` and `iw` differ when calling `precompute(expr, i, iw)` differ. We are working on fixing this code generation issue now. @Infinoid you are correct that the `isLowerable` failure from #347 is different since the  `i` and `iw` differing bug should still generate (albeit incorrect) code without any assertion errors

**Comment by Infinoid** [comment]
Looks like #459 fixed this.  Thanks @nirvikbaruah!
