### ISSUE TITLE
parallelizing over CPUVector fails

### ISSUE THREAD

**Issue by Infinoid** [tensor-compiler/taco#437]
CPUVector is one of the parallel units accepted by the `parallelize()` scheduling directive.  But it doesn't seem to work.  Here's a simple element-wise vector multiply:

```
% bin/taco "a(i) = b(i) * c(i)" "-s=parallelize(i,CPUVector,NoRaces)"

terminate called after throwing an instance of 'taco::TacoException'
  what():  Compiler bug at .../src/ir/ir.cpp:599 in make
Please report it to developers
 Condition failed: then.defined()
 
zsh: abort      bin/taco "a(i,j) = b(i,k) * c(k,j)" 
```

The same error occurs regardless of which OutputRaceStrategy I pass in the third argument.

https://github.com/tensor-compiler/taco/blob/master/src/ir/ir.cpp#L599 is in `IfThenElse::make(cond, then, otherwise)`.  It ensures that the `then` and `cond` parameters are defined.  When I add debugging print statements into it, I see that only `otherwise` parameter is defined:
```
cond = Expr()
then = Stmt()
otherwise = for (int32_t i = 0; i < c1_dimension; i++) {
  int32_t ia = 0 * a1_dimension + i;
  int32_t ib = 0 * b1_dimension + i;
  int32_t ic = 0 * c1_dimension + i;
  a_vals[ia] = b_vals[ib] * c_vals[ic];
}
```

Should this work?  Is there an example which shows this working?

**Comment by Infinoid** [comment]
I get the same error from this:

`bin/taco "a(i) = b(i) * c(i)" -s="unroll(i,4)"`

In both cases, the workaround seems to be doing a `split()` first, then `unroll`/`parallelize` over the inner index.

These both work:

`bin/taco "a(i) = b(i) * c(i)" -s="split(i,i0,i1,32),parallelize(i0,CPUVector,NoRaces)"`
`bin/taco "a(i) = b(i) * c(i)" -s="split(i,i0,i1,32),unroll(i0,4)"`

If the split is really necessary, could we print a better error message about this?

**Comment by rohany** [comment]
I think that the split needs to be done, as you can't necessarily vectorize a loop that doesn't have a constant width. The error message should definitely be better though. I don't know why the unroll is necessary though.

**Comment by Infinoid** [comment]
I don't think unroll is necessary for this particular kernel.  I was just trying to cook up a test case for `unroll()`, and noticed that it failed in the same way.

**Comment by rohany** [comment]
I see. Unroll has a similar reason as vectorization -- we can't unroll a non-statically bounded loop.

**Comment by Infinoid** [comment]
Makes sense.  Thanks for the responses, I'll see if I can give it a better error message.
