### ISSUE TITLE
Mixing Dense and Sparse in 'a(i) = b(i) + c(i)'

### ISSUE THREAD

**Issue by Lugatod** [tensor-compiler/taco#45]
The generated code for `taco "a(i) = b(i) + c(i)" -f=a:d -f=b:d -f=c:s` is wrong.

```c
ib = (ib + 1);
if (ic == ib)
   c1_ptr = (c1_ptr + 1);
```
should be
```c
if (ic == ib)
   c1_ptr = (c1_ptr + 1);
ib = (ib + 1);
```

**Comment by fredrikbk** [comment]
Fixed in 5d1097e. The fix is a bit hacky, but works. Will simplify again later.
