### ISSUE TITLE
Invalid dimensions when doing += on windowed lhs

### ISSUE THREAD

**Issue by stkaplan** [tensor-compiler/taco#451]
I'm trying to run a += expression where the LHS tensor uses windowing, and taco erroneously says it's invalid. Here's a reproducer:
```
int main()
{
    Tensor<double> A({8}, Format{Dense});
    Tensor<double> B({3}, Format{Dense});

    IndexVar i;
    A(i(0,3)) += B(i);
    A.compile();
    A.assemble();
    A.compute();
}
```

Running this gives the error:
```
terminate called after throwing an instance of 'taco::TacoException'
  what():  Compiler bug at /home/sam/work/taco/taco/src/index_notation/index_notation.cpp:2510 in makeConcreteNotation
Please report it to developers
 Condition failed: isReductionNotation(stmt, &reason)
 Not reduction notation: A0(i6) += A3(i6)
Dimension size mismatch. Index variable i6 is used to index modes of different dimensions (8 and 3).
Aborted
```

This works fine if I do `A(i(0,3)) = B(i)`, so I'm guessing this is an error in the += operator.

**Comment by stkaplan** [comment]
Note that it only seems to be a problem with the LHS. It works fine if I'm windowing on the right side, like this:

```
int main()
{
    Tensor<double> A({3}, Format{Dense});
    Tensor<double> B({8}, Format{Dense});

    IndexVar i;
    A(i) += B(i(0,3));
    A.compile();
    A.assemble();
    A.compute();
}
```

**Comment by rohany** [comment]
Thanks for the bug report, I've opened a PR to fix it!

**Comment by stkaplan** [comment]
The PR fixes that case, but causes a segfault in my actual program, which uses a vector of rows instead of the stride notation. Guess my reproducer was too simple :)

Try this:
```
int main()
{
    Tensor<double> A({8}, Format{Dense});
    Tensor<double> B({3}, Format{Dense});

    IndexVar i;
    A(i({1,3,6})) += B(i);
    A.compile();
    A.assemble();
    A.compute();
}
```

Running it in gdb gives:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff76ae5d6 in compute () from /tmp/taco_tmp_Dm2UFZ/j7ur7b124eaz.so
(gdb) bt
#0  0x00007ffff76ae5d6 in compute () from /tmp/taco_tmp_Dm2UFZ/j7ur7b124eaz.so
#1  0x00007ffff7c31214 in taco::ir::Module::callFuncPackedRaw (this=0x555555594af0, name="_shim_compute", args=0x55555558a500)
    at /home/sam/work/taco/taco/src/codegen/module.cpp:203
#2  0x00007ffff7ba6648 in taco::ir::Module::callFuncPacked (this=0x555555594af0, name="compute", args=0x55555558a500)
    at /home/sam/work/taco/taco/include/taco/codegen/module.h:58
#3  0x00007ffff7ba05e4 in taco::TensorBase::compute (this=0x7fffffffdaa0) at /home/sam/work/taco/taco/src/tensor.cpp:817
#4  0x0000555555562975 in main () at bug.cpp:14
```

Same segfault happens if I pass in an `std::vector<int>` with the row numbers. I'll attach the generated code, but I'm not really sure if I can debug it further.

[j7ur7b124eaz.txt](https://github.com/tensor-compiler/taco/files/6370728/j7ur7b124eaz.txt)

**Comment by rohany** [comment]
I've updated the patch to fix this bug as well, thanks for finding it! Looking at the generated code however, I still don't think it's going to do what you're expecting (the generated compute kernel is still zeroing out the values of A). But it would be better to open a separate issue about that problem.
