### ISSUE TITLE
CUDA regression in tensor.recompile, expr.reduction0 and others

### ISSUE THREAD

**Issue by Infinoid** [tensor-compiler/taco#456]
e94e68e fixed #454, but introduced some new failures.

Here is the list of new failures:

```
	 15 - expr.reduction0 (Failed)
	 26 - */expr.storage/* (Failed)
	 59 - */lower.compile/* (Failed)
	 67 - */parafac.eval/* (Failed)
	 68 - qcd.mul0 (Failed)
	 69 - qcd.mul1 (Failed)
	 70 - qcd.mul2 (Failed)
	139 - tensor.skip_recompile (Failed)
	140 - tensor.recompile (Failed)
	191 - pytaco (Child aborted)
```

There are some existing failures in the windowing tests, see #426 for some of those.

The full test log is here: https://gist.github.com/Infinoid/0a56eb158356ae499c88bd9be0366937

I am running with gcc 10.2.0 and cuda 11.2.  TACO is configured with `-DCMAKE_BUILD_TYPE=Debug -DCUDA=ON -DOPENMP=ON -DPYTHON=ON`.

**Comment by stephenchouca** [comment]
The latest commit should fix all the CUDA tests other than the windowing tests (in particular, `*/stride.windowing/*`, `*/indexSetVectors.windowing/*`, and `*/indexSetMatrices.windowing/*`), which I believe are all related to #426. @rohany let me know if that's not the case.

**Comment by rohany** [comment]
`stride.windowing` is definitely related to #426, but I haven't looked into the other two. It's definitely possible that the break/continue problem in 426 is the cause of those failures though.

**Comment by Infinoid** [comment]
I re-ran tests with `-DCUDA=ON` and confirmed that all of the new regressions have been fixed.  Only the windowing failures remain.

```
98% tests passed, 3 tests failed out of 181

Total Test time (real) = 523.25 sec

The following tests did not run:
	 17 - expr.accumulate (Disabled)
	 27 - format.mm_permute_formats (Disabled)
	 71 - qcd.mul3 (Disabled)
	 94 - generate_evaluation_files.cpu (Disabled)
	 95 - generate_evaluation_files.gpu (Disabled)
	 96 - generate_figures.cpu (Disabled)
	151 - tensor_types.complex_mul_scalar (Disabled)
	156 - tensor_types.coordinate_types (Disabled)
	162 - lower.transpose (Disabled)
	163 - lower.transpose2 (Disabled)
	164 - lower.transpose3 (Disabled)

The following tests FAILED:
	183 - */stride.windowing/* (Failed)
	184 - */indexSetVectors.windowing/* (Failed)
	185 - */indexSetMatrices.windowing/* (Failed)
```

Thanks!
