### ISSUE TITLE
How to check the code generated by TACO after scheduling

### ISSUE THREAD

**Issue by zhang677** [tensor-compiler/taco#488]
I've been reading the [docs ](http://tensor-compiler.org/docs/scheduling/index.html)and find the code like this:
```
for (int32_t i = 0; i < A1_dimension; i++) {
    for (int32_t jA = A2_pos[i]; jA < A2_pos[(i + 1)]; jA++) {
        int32_t j = A2_crd[jA];
        y_vals[i] = y_vals[i] + A_vals[jA] * x_vals[j];
    }
}
```
But I don't know which C++ API to use to print such code( for CUDA , to be specific), since I want to try some ways of scheduling besides what the [online-codegen tool](http://tensor-compiler.org/codegen.html) provides.

**Comment by rohany** [comment]
After you use `.compile()` , you can use `.getSource()` on the tensor being assigned to get a `std::string` containing the generated source code.

**Comment by zhang677** [comment]
OK! Thanks you very much!
