### ISSUE TITLE
How to use TACO for BCSR format?

### ISSUE THREAD

**Issue by densamoilov** [tensor-compiler/taco#498]
I'm looking for a clarification on using blocked sparse matrix storage formats in TACO, namely `BCSR`.
Suppose we want to define a matrix multiplication operation: `C = A * B`, where `C` and `B` are dense matrices and `A` is a sparse one.
Using the TACO formats I'm describing the matrices as follows:
- `C` and `B` -  `{Dense, Dense}`
- `A` -  `{Dense, Sparse, Dense, Dense}`
So basically, the first two dimensions of the matrix `A` describe a `CSR` matrix that contains positions of the dense sub-matrices. The size of the sub-matrices is defined via the 3rd and 4th dimensions.

How can I define the matrix multiplication operation using index notation?

**Comment by rohany** [comment]
To do this, you'll need to also block the C and B matrices to match the dimensionality of the blocked A matrix. Once you do this, a kernel like: `C(io, jo, ii, ji) = A(io, ko, ii, ki) * B(ko, jo, ki, ji)` should be what you want. This is derived from the kernel `C(i, j) = A(i, k) * B(k, j)`, where the `i, j, k` index variables have been blocked out into inner and outer variables.

**Comment by stephenchouca** [comment]
Note that if you don't need `B` and `C` to be tiled as well, then something like [this](http://tensor-compiler.org/codegen.html?expr=C(io,ii,k)%20=%20A(io,jo,ii,ji)%20*%20B(jo,ji,k)&format=C:ddd:0,1,2;A:dsdd:0,1,2,3;B:ddd:0,1,2) might also suffice. (As @rohany points out though, the `i` and `j` dimensions of `C` and `B` still need to be split in the same way as `A`.)

**Comment by rohany** [comment]
Closing this since I think it has been answered.
