### ISSUE TITLE
How can I get the length of any dimension of a tensor?

### ISSUE THREAD

**Issue by FreemanTheMaverick** [tensor-compiler/taco#502]
How can I get the length of any dimension of a tensor? Is there a function like Eigen3's `matrix.rows()` in taco?

**Comment by rohany** [comment]
Use the `getDimension(int mode)` function available on a `Tensor`.

**Comment by FreemanTheMaverick** [comment]
> Use the `getDimension(int mode)` function available on a `Tensor`.

Thank you.
