### ISSUE TITLE
What is the fillvalue meaning

### ISSUE THREAD

**Issue by LeiWang1999** [tensor-compiler/taco#517]
Suppose that I create a Tensor A and then I use fillTensor to fill the Tensor, but I'm confused about what this value `fillvalue` means.

For example:

```C++
Tensor <double> A("A", {2,6}, csr);
util::fillTensor(A,util::FillMethod::Dense, 0.5);
```

from my heuristic point of view, the fillvalue may represent the value that used to fill the tensor, and the expected tensor should be `[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 ]` but actually this methods returns the non-zero value's density `[2.84614e+06, -5.28081e+06, -6.82125e+06, 0, 0, 0, 4.78938e+06, -1.31094e+06, -4.50599e+06, 0, 0, 0]`

```C++
    case FillMethod::Dense: {
      for (int i=0; i<tensorSize[0]; i++) {
        for (int j=0; j<(fillValue*tensorSize[1]); j++) {
          tens.insert({i,j}, unif(re));
        }
      }
```

but when I use the util::FillMethod::Sparse 

```C++
  case FillMethod::Sparse:
  case FillMethod::HyperSparse: {
    for (int i=0; i<(fillValue*tensorSize[0]); i++) {
      for (int j=0; j<(fillValue*tensorSize[1]); j++) {
        tens.insert({positions[0][i],positions[1][j]}, unif(re));
      }
      std::random_shuffle(positions[1].begin(),positions[1].end());
    }
    break;
  }
```

and it returns `[2.04073e+06, -4.67737e+06, 0, 4.46838e+06, 0, 0, 0, 0, 0, 0, 0, 0]`

which fillVlaue here reperents the density^2 of the tensor. Why is it designed this way？

**Comment by LeiWang1999** [comment]
please cc, @fredrikbk

**Comment by rohany** [comment]
As you've said, the `fillValue` parameter to the `util::fill*` methods appears to be the non-zero density -- it's just a variable that isn't well named.

**Comment by LeiWang1999** [comment]
@rohany  Thanks for reply, but for high dimensional tensor,  it represents density^(dimensions).. I do not this is a good design.
