### ISSUE TITLE
Convert raw pointer to 2nd order tensor

### ISSUE THREAD

**Issue by miaodi** [tensor-compiler/taco#529]
Hi,

I just tried this tensor library and found it is very convenient. I am using Eigen to do most of the matrix operation. And I am looking for some ways to convert an Eigen matrix to a 2nd order dense tensor in taco so that I can do contraction between a 4th order tensor and a second order tensor generated by Eigen without a copy operation.

Thank you

Di

**Comment by stephenchouca** [comment]
[This part of the documentation](http://tensor-compiler.org/docs/controlling_memory.html#dense-vectors) describes how you can cast dense arrays as TACO tensors without incurring a copy. (The example shows a dense vector, but the same code should work for multidimensional tensors as well as long as the dense array is still a flat array.)
