### ISSUE TITLE
taco tool `-read-source` no longer works

### ISSUE THREAD

**Issue by shoaibkamil** [tensor-compiler/taco#87]
`-read-source` bypasses the shim generation mechanisms in the backend.  The tool should use `CodeGen_C::generateShim()`, a static function, to generate shims for the function signatures required.  Since the compiled output, in this case, is not visible to the user, it's ok to directly append these shims to the source that was read in.

**Comment by fredrikbk** [comment]
593d937 makes TensorBase::compileSource generate shim functions and build a string containing everything that is passed to `Module::setSource`. However, the resulting `.c` files are empty, so it looks like the code get's lost somewhere inside `Module`.

**Comment by shoaibkamil** [comment]
Fixed by 4c68648.
